/*
 * University of Illinois Open Source License
 * Copyright 2011 Luthey-Schulten Group,
 * All rights reserved.
 * 
 * Developed by: Luthey-Schulten Group
 * 			     University of Illinois at Urbana-Champaign
 * 			     http://www.scs.uiuc.edu/~schulten
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the Software), to deal with 
 * the Software without restriction, including without limitation the rights to 
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
 * of the Software, and to permit persons to whom the Software is furnished to 
 * do so, subject to the following conditions:
 * 
 * - Redistributions of source code must retain the above copyright notice, 
 * this list of conditions and the following disclaimers.
 * 
 * - Redistributions in binary form must reproduce the above copyright notice, 
 * this list of conditions and the following disclaimers in the documentation 
 * and/or other materials provided with the distribution.
 * 
 * - Neither the names of the Luthey-Schulten Group, University of Illinois at
 * Urbana-Champaign, nor the names of its contributors may be used to endorse or
 * promote products derived from this Software without specific prior written
 * permission.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL 
 * THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR 
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
 * OTHER DEALINGS WITH THE SOFTWARE.
 *
 * Author(s): Elijah Roberts, Max Klein
 */
 
package lm.io;

import "lm/io/TilingHist.proto";

message FFluxOutput {

	enum Direction {
        FORWARD		= 0;
        BACKWARD 	= 1;
    }
    
    enum Lifecycle {
    	INITIAL		= 0;
    	FINAL		= 1;
    }

	message TrajectoryOutput {
		// holds a number of pairs of long, single column tables
		// one row per trajectory

		optional Direction direction	= 1 [default=FORWARD];
		optional Lifecycle lifecycle	= 2 [default=INITIAL];
		
		repeated double count			= 101;
		repeated uint64 edge_id			= 102;
		repeated double species_count	= 103 [packed=true];
		repeated double time			= 104;
		repeated uint64 trajectory_id	= 105;
	}
	
	message BasinOutput {
		optional Direction direction 							= 1 [default=FORWARD];
		
		optional double phase_0_flux 							= 101;
		optional double switching_rate_constant					= 102;
		
		optional lm.io.TilingHist probability_i_to_i_plus_one 	= 201;
		// the starting basin-depedent probability
		optional lm.io.TilingHist probability_i			= 202;
	}
	
	message FinalOutput {
		// the normalized, starting basin-independent probability
		optional lm.io.TilingHist probability_i	= 1;
	}
	
	// for a 1D tiling, this is going to be tiling->edges_size() + 1
	optional int32 number_species					= 1 [default=0];
	optional uint64 number_tiles	 				= 2 [default=0];
    optional uint32 tiling_id      					= 3 [default=0];
    
    repeated TrajectoryOutput trajectory_outputs 	= 101;
    repeated BasinOutput basin_outputs				= 102;
    optional FinalOutput final_output				= 103;
}
