/*
 * Copyright 2012-2016 Johns Hopkins University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Developed by: Roberts Group
 *               Johns Hopkins University
 *               http://biophysics.jhu.edu/roberts/
 *
 * Author(s): Elijah Roberts, Max Klein
 */
syntax = "proto2";
package lm.types;

import "lm/types/ArrayOrdering.proto";

message Lattice {

    required int32 lattice_x_size                   = 1;
    required int32 lattice_y_size                   = 2;
    required int32 lattice_z_size                   = 3;
    optional int32 particles_per_site               = 4;
    optional ArrayOrdering particles_ordering       = 5;
    optional bool particles_compressed_deflate      = 9 [default = false];
    optional bytes particles                        = 6;
    optional ArrayOrdering sites_ordering           = 7;
    optional bool sites_compressed_deflate          = 10 [default = false];
    optional bytes sites                            = 8;
}
