// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/io/FirstPassageTimes.proto

#ifndef PROTOBUF_lm_2fio_2fFirstPassageTimes_2eproto__INCLUDED
#define PROTOBUF_lm_2fio_2fFirstPassageTimes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fio_2fFirstPassageTimes_2eproto();
void protobuf_AssignDesc_lm_2fio_2fFirstPassageTimes_2eproto();
void protobuf_ShutdownFile_lm_2fio_2fFirstPassageTimes_2eproto();

class FirstPassageTimes;

// ===================================================================

class FirstPassageTimes : public ::google::protobuf::Message {
 public:
  FirstPassageTimes();
  virtual ~FirstPassageTimes();
  
  FirstPassageTimes(const FirstPassageTimes& from);
  
  inline FirstPassageTimes& operator=(const FirstPassageTimes& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FirstPassageTimes& default_instance();
  
  void Swap(FirstPassageTimes* other);
  
  // implements Message ----------------------------------------------
  
  FirstPassageTimes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FirstPassageTimes& from);
  void MergeFrom(const FirstPassageTimes& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 species = 1;
  inline bool has_species() const;
  inline void clear_species();
  static const int kSpeciesFieldNumber = 1;
  inline ::google::protobuf::uint32 species() const;
  inline void set_species(::google::protobuf::uint32 value);
  
  // repeated uint32 species_count = 2 [packed = true];
  inline int species_count_size() const;
  inline void clear_species_count();
  static const int kSpeciesCountFieldNumber = 2;
  inline ::google::protobuf::uint32 species_count(int index) const;
  inline void set_species_count(int index, ::google::protobuf::uint32 value);
  inline void add_species_count(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      species_count() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_species_count();
  
  // repeated double first_passage_time = 3 [packed = true];
  inline int first_passage_time_size() const;
  inline void clear_first_passage_time();
  static const int kFirstPassageTimeFieldNumber = 3;
  inline double first_passage_time(int index) const;
  inline void set_first_passage_time(int index, double value);
  inline void add_first_passage_time(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      first_passage_time() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_first_passage_time();
  
  // @@protoc_insertion_point(class_scope:lm.io.FirstPassageTimes)
 private:
  inline void set_has_species();
  inline void clear_has_species();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > species_count_;
  mutable int _species_count_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > first_passage_time_;
  mutable int _first_passage_time_cached_byte_size_;
  ::google::protobuf::uint32 species_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fFirstPassageTimes_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fFirstPassageTimes_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fFirstPassageTimes_2eproto();
  
  void InitAsDefaultInstance();
  static FirstPassageTimes* default_instance_;
};
// ===================================================================


// ===================================================================

// FirstPassageTimes

// required uint32 species = 1;
inline bool FirstPassageTimes::has_species() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FirstPassageTimes::set_has_species() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FirstPassageTimes::clear_has_species() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FirstPassageTimes::clear_species() {
  species_ = 0u;
  clear_has_species();
}
inline ::google::protobuf::uint32 FirstPassageTimes::species() const {
  return species_;
}
inline void FirstPassageTimes::set_species(::google::protobuf::uint32 value) {
  set_has_species();
  species_ = value;
}

// repeated uint32 species_count = 2 [packed = true];
inline int FirstPassageTimes::species_count_size() const {
  return species_count_.size();
}
inline void FirstPassageTimes::clear_species_count() {
  species_count_.Clear();
}
inline ::google::protobuf::uint32 FirstPassageTimes::species_count(int index) const {
  return species_count_.Get(index);
}
inline void FirstPassageTimes::set_species_count(int index, ::google::protobuf::uint32 value) {
  species_count_.Set(index, value);
}
inline void FirstPassageTimes::add_species_count(::google::protobuf::uint32 value) {
  species_count_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
FirstPassageTimes::species_count() const {
  return species_count_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
FirstPassageTimes::mutable_species_count() {
  return &species_count_;
}

// repeated double first_passage_time = 3 [packed = true];
inline int FirstPassageTimes::first_passage_time_size() const {
  return first_passage_time_.size();
}
inline void FirstPassageTimes::clear_first_passage_time() {
  first_passage_time_.Clear();
}
inline double FirstPassageTimes::first_passage_time(int index) const {
  return first_passage_time_.Get(index);
}
inline void FirstPassageTimes::set_first_passage_time(int index, double value) {
  first_passage_time_.Set(index, value);
}
inline void FirstPassageTimes::add_first_passage_time(double value) {
  first_passage_time_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
FirstPassageTimes::first_passage_time() const {
  return first_passage_time_;
}
inline ::google::protobuf::RepeatedField< double >*
FirstPassageTimes::mutable_first_passage_time() {
  return &first_passage_time_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fio_2fFirstPassageTimes_2eproto__INCLUDED
