// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/io/Lattice.proto

#ifndef PROTOBUF_lm_2fio_2fLattice_2eproto__INCLUDED
#define PROTOBUF_lm_2fio_2fLattice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fio_2fLattice_2eproto();
void protobuf_AssignDesc_lm_2fio_2fLattice_2eproto();
void protobuf_ShutdownFile_lm_2fio_2fLattice_2eproto();

class Lattice;

// ===================================================================

class Lattice : public ::google::protobuf::Message {
 public:
  Lattice();
  virtual ~Lattice();
  
  Lattice(const Lattice& from);
  
  inline Lattice& operator=(const Lattice& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Lattice& default_instance();
  
  void Swap(Lattice* other);
  
  // implements Message ----------------------------------------------
  
  Lattice* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Lattice& from);
  void MergeFrom(const Lattice& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 lattice_x_size = 1;
  inline bool has_lattice_x_size() const;
  inline void clear_lattice_x_size();
  static const int kLatticeXSizeFieldNumber = 1;
  inline ::google::protobuf::uint32 lattice_x_size() const;
  inline void set_lattice_x_size(::google::protobuf::uint32 value);
  
  // required uint32 lattice_y_size = 2;
  inline bool has_lattice_y_size() const;
  inline void clear_lattice_y_size();
  static const int kLatticeYSizeFieldNumber = 2;
  inline ::google::protobuf::uint32 lattice_y_size() const;
  inline void set_lattice_y_size(::google::protobuf::uint32 value);
  
  // required uint32 lattice_z_size = 3;
  inline bool has_lattice_z_size() const;
  inline void clear_lattice_z_size();
  static const int kLatticeZSizeFieldNumber = 3;
  inline ::google::protobuf::uint32 lattice_z_size() const;
  inline void set_lattice_z_size(::google::protobuf::uint32 value);
  
  // required uint32 particles_per_site = 4;
  inline bool has_particles_per_site() const;
  inline void clear_particles_per_site();
  static const int kParticlesPerSiteFieldNumber = 4;
  inline ::google::protobuf::uint32 particles_per_site() const;
  inline void set_particles_per_site(::google::protobuf::uint32 value);
  
  // required double time = 5;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 5;
  inline double time() const;
  inline void set_time(double value);
  
  // @@protoc_insertion_point(class_scope:lm.io.Lattice)
 private:
  inline void set_has_lattice_x_size();
  inline void clear_has_lattice_x_size();
  inline void set_has_lattice_y_size();
  inline void clear_has_lattice_y_size();
  inline void set_has_lattice_z_size();
  inline void clear_has_lattice_z_size();
  inline void set_has_particles_per_site();
  inline void clear_has_particles_per_site();
  inline void set_has_time();
  inline void clear_has_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 lattice_x_size_;
  ::google::protobuf::uint32 lattice_y_size_;
  ::google::protobuf::uint32 lattice_z_size_;
  ::google::protobuf::uint32 particles_per_site_;
  double time_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fLattice_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fLattice_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fLattice_2eproto();
  
  void InitAsDefaultInstance();
  static Lattice* default_instance_;
};
// ===================================================================


// ===================================================================

// Lattice

// required uint32 lattice_x_size = 1;
inline bool Lattice::has_lattice_x_size() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Lattice::set_has_lattice_x_size() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Lattice::clear_has_lattice_x_size() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Lattice::clear_lattice_x_size() {
  lattice_x_size_ = 0u;
  clear_has_lattice_x_size();
}
inline ::google::protobuf::uint32 Lattice::lattice_x_size() const {
  return lattice_x_size_;
}
inline void Lattice::set_lattice_x_size(::google::protobuf::uint32 value) {
  set_has_lattice_x_size();
  lattice_x_size_ = value;
}

// required uint32 lattice_y_size = 2;
inline bool Lattice::has_lattice_y_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Lattice::set_has_lattice_y_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Lattice::clear_has_lattice_y_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Lattice::clear_lattice_y_size() {
  lattice_y_size_ = 0u;
  clear_has_lattice_y_size();
}
inline ::google::protobuf::uint32 Lattice::lattice_y_size() const {
  return lattice_y_size_;
}
inline void Lattice::set_lattice_y_size(::google::protobuf::uint32 value) {
  set_has_lattice_y_size();
  lattice_y_size_ = value;
}

// required uint32 lattice_z_size = 3;
inline bool Lattice::has_lattice_z_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Lattice::set_has_lattice_z_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Lattice::clear_has_lattice_z_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Lattice::clear_lattice_z_size() {
  lattice_z_size_ = 0u;
  clear_has_lattice_z_size();
}
inline ::google::protobuf::uint32 Lattice::lattice_z_size() const {
  return lattice_z_size_;
}
inline void Lattice::set_lattice_z_size(::google::protobuf::uint32 value) {
  set_has_lattice_z_size();
  lattice_z_size_ = value;
}

// required uint32 particles_per_site = 4;
inline bool Lattice::has_particles_per_site() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Lattice::set_has_particles_per_site() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Lattice::clear_has_particles_per_site() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Lattice::clear_particles_per_site() {
  particles_per_site_ = 0u;
  clear_has_particles_per_site();
}
inline ::google::protobuf::uint32 Lattice::particles_per_site() const {
  return particles_per_site_;
}
inline void Lattice::set_particles_per_site(::google::protobuf::uint32 value) {
  set_has_particles_per_site();
  particles_per_site_ = value;
}

// required double time = 5;
inline bool Lattice::has_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Lattice::set_has_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Lattice::clear_has_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Lattice::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline double Lattice::time() const {
  return time_;
}
inline void Lattice::set_time(double value) {
  set_has_time();
  time_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fio_2fLattice_2eproto__INCLUDED
