// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/io/ParameterValues.proto

#ifndef PROTOBUF_lm_2fio_2fParameterValues_2eproto__INCLUDED
#define PROTOBUF_lm_2fio_2fParameterValues_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fio_2fParameterValues_2eproto();
void protobuf_AssignDesc_lm_2fio_2fParameterValues_2eproto();
void protobuf_ShutdownFile_lm_2fio_2fParameterValues_2eproto();

class ParameterValues;

// ===================================================================

class ParameterValues : public ::google::protobuf::Message {
 public:
  ParameterValues();
  virtual ~ParameterValues();
  
  ParameterValues(const ParameterValues& from);
  
  inline ParameterValues& operator=(const ParameterValues& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ParameterValues& default_instance();
  
  void Swap(ParameterValues* other);
  
  // implements Message ----------------------------------------------
  
  ParameterValues* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParameterValues& from);
  void MergeFrom(const ParameterValues& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string parameter = 1;
  inline bool has_parameter() const;
  inline void clear_parameter();
  static const int kParameterFieldNumber = 1;
  inline const ::std::string& parameter() const;
  inline void set_parameter(const ::std::string& value);
  inline void set_parameter(const char* value);
  inline void set_parameter(const char* value, size_t size);
  inline ::std::string* mutable_parameter();
  inline ::std::string* release_parameter();
  
  // repeated double value = 2 [packed = true];
  inline int value_size() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline double value(int index) const;
  inline void set_value(int index, double value);
  inline void add_value(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      value() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_value();
  
  // repeated double time = 3 [packed = true];
  inline int time_size() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 3;
  inline double time(int index) const;
  inline void set_time(int index, double value);
  inline void add_time(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      time() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_time();
  
  // @@protoc_insertion_point(class_scope:lm.io.ParameterValues)
 private:
  inline void set_has_parameter();
  inline void clear_has_parameter();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* parameter_;
  ::google::protobuf::RepeatedField< double > value_;
  mutable int _value_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > time_;
  mutable int _time_cached_byte_size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fParameterValues_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fParameterValues_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fParameterValues_2eproto();
  
  void InitAsDefaultInstance();
  static ParameterValues* default_instance_;
};
// ===================================================================


// ===================================================================

// ParameterValues

// required string parameter = 1;
inline bool ParameterValues::has_parameter() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParameterValues::set_has_parameter() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParameterValues::clear_has_parameter() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParameterValues::clear_parameter() {
  if (parameter_ != &::google::protobuf::internal::kEmptyString) {
    parameter_->clear();
  }
  clear_has_parameter();
}
inline const ::std::string& ParameterValues::parameter() const {
  return *parameter_;
}
inline void ParameterValues::set_parameter(const ::std::string& value) {
  set_has_parameter();
  if (parameter_ == &::google::protobuf::internal::kEmptyString) {
    parameter_ = new ::std::string;
  }
  parameter_->assign(value);
}
inline void ParameterValues::set_parameter(const char* value) {
  set_has_parameter();
  if (parameter_ == &::google::protobuf::internal::kEmptyString) {
    parameter_ = new ::std::string;
  }
  parameter_->assign(value);
}
inline void ParameterValues::set_parameter(const char* value, size_t size) {
  set_has_parameter();
  if (parameter_ == &::google::protobuf::internal::kEmptyString) {
    parameter_ = new ::std::string;
  }
  parameter_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ParameterValues::mutable_parameter() {
  set_has_parameter();
  if (parameter_ == &::google::protobuf::internal::kEmptyString) {
    parameter_ = new ::std::string;
  }
  return parameter_;
}
inline ::std::string* ParameterValues::release_parameter() {
  clear_has_parameter();
  if (parameter_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = parameter_;
    parameter_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated double value = 2 [packed = true];
inline int ParameterValues::value_size() const {
  return value_.size();
}
inline void ParameterValues::clear_value() {
  value_.Clear();
}
inline double ParameterValues::value(int index) const {
  return value_.Get(index);
}
inline void ParameterValues::set_value(int index, double value) {
  value_.Set(index, value);
}
inline void ParameterValues::add_value(double value) {
  value_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
ParameterValues::value() const {
  return value_;
}
inline ::google::protobuf::RepeatedField< double >*
ParameterValues::mutable_value() {
  return &value_;
}

// repeated double time = 3 [packed = true];
inline int ParameterValues::time_size() const {
  return time_.size();
}
inline void ParameterValues::clear_time() {
  time_.Clear();
}
inline double ParameterValues::time(int index) const {
  return time_.Get(index);
}
inline void ParameterValues::set_time(int index, double value) {
  time_.Set(index, value);
}
inline void ParameterValues::add_time(double value) {
  time_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
ParameterValues::time() const {
  return time_;
}
inline ::google::protobuf::RepeatedField< double >*
ParameterValues::mutable_time() {
  return &time_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fio_2fParameterValues_2eproto__INCLUDED
