// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/io/ReactionModel.proto

#ifndef PROTOBUF_lm_2fio_2fReactionModel_2eproto__INCLUDED
#define PROTOBUF_lm_2fio_2fReactionModel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto();
void protobuf_AssignDesc_lm_2fio_2fReactionModel_2eproto();
void protobuf_ShutdownFile_lm_2fio_2fReactionModel_2eproto();

class ReactionModel;
class ReactionModel_Reaction;

// ===================================================================

class ReactionModel_Reaction : public ::google::protobuf::Message {
 public:
  ReactionModel_Reaction();
  virtual ~ReactionModel_Reaction();
  
  ReactionModel_Reaction(const ReactionModel_Reaction& from);
  
  inline ReactionModel_Reaction& operator=(const ReactionModel_Reaction& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReactionModel_Reaction& default_instance();
  
  void Swap(ReactionModel_Reaction* other);
  
  // implements Message ----------------------------------------------
  
  ReactionModel_Reaction* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReactionModel_Reaction& from);
  void MergeFrom(const ReactionModel_Reaction& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);
  
  // repeated double rate_constant = 2 [packed = true];
  inline int rate_constant_size() const;
  inline void clear_rate_constant();
  static const int kRateConstantFieldNumber = 2;
  inline double rate_constant(int index) const;
  inline void set_rate_constant(int index, double value);
  inline void add_rate_constant(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      rate_constant() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_rate_constant();
  
  // optional bool rate_has_noise = 3 [default = false];
  inline bool has_rate_has_noise() const;
  inline void clear_rate_has_noise();
  static const int kRateHasNoiseFieldNumber = 3;
  inline bool rate_has_noise() const;
  inline void set_rate_has_noise(bool value);
  
  // optional double rate_noise_variance = 4;
  inline bool has_rate_noise_variance() const;
  inline void clear_rate_noise_variance();
  static const int kRateNoiseVarianceFieldNumber = 4;
  inline double rate_noise_variance() const;
  inline void set_rate_noise_variance(double value);
  
  // optional double rate_noise_tau = 5;
  inline bool has_rate_noise_tau() const;
  inline void clear_rate_noise_tau();
  static const int kRateNoiseTauFieldNumber = 5;
  inline double rate_noise_tau() const;
  inline void set_rate_noise_tau(double value);
  
  // @@protoc_insertion_point(class_scope:lm.io.ReactionModel.Reaction)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_rate_has_noise();
  inline void clear_has_rate_has_noise();
  inline void set_has_rate_noise_variance();
  inline void clear_has_rate_noise_variance();
  inline void set_has_rate_noise_tau();
  inline void clear_has_rate_noise_tau();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< double > rate_constant_;
  mutable int _rate_constant_cached_byte_size_;
  ::google::protobuf::uint32 type_;
  bool rate_has_noise_;
  double rate_noise_variance_;
  double rate_noise_tau_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fReactionModel_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fReactionModel_2eproto();
  
  void InitAsDefaultInstance();
  static ReactionModel_Reaction* default_instance_;
};
// -------------------------------------------------------------------

class ReactionModel : public ::google::protobuf::Message {
 public:
  ReactionModel();
  virtual ~ReactionModel();
  
  ReactionModel(const ReactionModel& from);
  
  inline ReactionModel& operator=(const ReactionModel& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReactionModel& default_instance();
  
  void Swap(ReactionModel* other);
  
  // implements Message ----------------------------------------------
  
  ReactionModel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReactionModel& from);
  void MergeFrom(const ReactionModel& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ReactionModel_Reaction Reaction;
  
  // accessors -------------------------------------------------------
  
  // required uint32 number_species = 1;
  inline bool has_number_species() const;
  inline void clear_number_species();
  static const int kNumberSpeciesFieldNumber = 1;
  inline ::google::protobuf::uint32 number_species() const;
  inline void set_number_species(::google::protobuf::uint32 value);
  
  // required uint32 number_reactions = 2;
  inline bool has_number_reactions() const;
  inline void clear_number_reactions();
  static const int kNumberReactionsFieldNumber = 2;
  inline ::google::protobuf::uint32 number_reactions() const;
  inline void set_number_reactions(::google::protobuf::uint32 value);
  
  // repeated uint32 initial_species_count = 3 [packed = true];
  inline int initial_species_count_size() const;
  inline void clear_initial_species_count();
  static const int kInitialSpeciesCountFieldNumber = 3;
  inline ::google::protobuf::uint32 initial_species_count(int index) const;
  inline void set_initial_species_count(int index, ::google::protobuf::uint32 value);
  inline void add_initial_species_count(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      initial_species_count() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_initial_species_count();
  
  // repeated .lm.io.ReactionModel.Reaction reaction = 4;
  inline int reaction_size() const;
  inline void clear_reaction();
  static const int kReactionFieldNumber = 4;
  inline const ::lm::io::ReactionModel_Reaction& reaction(int index) const;
  inline ::lm::io::ReactionModel_Reaction* mutable_reaction(int index);
  inline ::lm::io::ReactionModel_Reaction* add_reaction();
  inline const ::google::protobuf::RepeatedPtrField< ::lm::io::ReactionModel_Reaction >&
      reaction() const;
  inline ::google::protobuf::RepeatedPtrField< ::lm::io::ReactionModel_Reaction >*
      mutable_reaction();
  
  // repeated int32 stoichiometric_matrix = 5 [packed = true];
  inline int stoichiometric_matrix_size() const;
  inline void clear_stoichiometric_matrix();
  static const int kStoichiometricMatrixFieldNumber = 5;
  inline ::google::protobuf::int32 stoichiometric_matrix(int index) const;
  inline void set_stoichiometric_matrix(int index, ::google::protobuf::int32 value);
  inline void add_stoichiometric_matrix(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      stoichiometric_matrix() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_stoichiometric_matrix();
  
  // repeated uint32 dependency_matrix = 6 [packed = true];
  inline int dependency_matrix_size() const;
  inline void clear_dependency_matrix();
  static const int kDependencyMatrixFieldNumber = 6;
  inline ::google::protobuf::uint32 dependency_matrix(int index) const;
  inline void set_dependency_matrix(int index, ::google::protobuf::uint32 value);
  inline void add_dependency_matrix(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      dependency_matrix() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_dependency_matrix();
  
  // @@protoc_insertion_point(class_scope:lm.io.ReactionModel)
 private:
  inline void set_has_number_species();
  inline void clear_has_number_species();
  inline void set_has_number_reactions();
  inline void clear_has_number_reactions();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 number_species_;
  ::google::protobuf::uint32 number_reactions_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > initial_species_count_;
  mutable int _initial_species_count_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::lm::io::ReactionModel_Reaction > reaction_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > stoichiometric_matrix_;
  mutable int _stoichiometric_matrix_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > dependency_matrix_;
  mutable int _dependency_matrix_cached_byte_size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fReactionModel_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fReactionModel_2eproto();
  
  void InitAsDefaultInstance();
  static ReactionModel* default_instance_;
};
// ===================================================================


// ===================================================================

// ReactionModel_Reaction

// required uint32 type = 1;
inline bool ReactionModel_Reaction::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReactionModel_Reaction::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReactionModel_Reaction::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReactionModel_Reaction::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 ReactionModel_Reaction::type() const {
  return type_;
}
inline void ReactionModel_Reaction::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
}

// repeated double rate_constant = 2 [packed = true];
inline int ReactionModel_Reaction::rate_constant_size() const {
  return rate_constant_.size();
}
inline void ReactionModel_Reaction::clear_rate_constant() {
  rate_constant_.Clear();
}
inline double ReactionModel_Reaction::rate_constant(int index) const {
  return rate_constant_.Get(index);
}
inline void ReactionModel_Reaction::set_rate_constant(int index, double value) {
  rate_constant_.Set(index, value);
}
inline void ReactionModel_Reaction::add_rate_constant(double value) {
  rate_constant_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
ReactionModel_Reaction::rate_constant() const {
  return rate_constant_;
}
inline ::google::protobuf::RepeatedField< double >*
ReactionModel_Reaction::mutable_rate_constant() {
  return &rate_constant_;
}

// optional bool rate_has_noise = 3 [default = false];
inline bool ReactionModel_Reaction::has_rate_has_noise() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReactionModel_Reaction::set_has_rate_has_noise() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ReactionModel_Reaction::clear_has_rate_has_noise() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ReactionModel_Reaction::clear_rate_has_noise() {
  rate_has_noise_ = false;
  clear_has_rate_has_noise();
}
inline bool ReactionModel_Reaction::rate_has_noise() const {
  return rate_has_noise_;
}
inline void ReactionModel_Reaction::set_rate_has_noise(bool value) {
  set_has_rate_has_noise();
  rate_has_noise_ = value;
}

// optional double rate_noise_variance = 4;
inline bool ReactionModel_Reaction::has_rate_noise_variance() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ReactionModel_Reaction::set_has_rate_noise_variance() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ReactionModel_Reaction::clear_has_rate_noise_variance() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ReactionModel_Reaction::clear_rate_noise_variance() {
  rate_noise_variance_ = 0;
  clear_has_rate_noise_variance();
}
inline double ReactionModel_Reaction::rate_noise_variance() const {
  return rate_noise_variance_;
}
inline void ReactionModel_Reaction::set_rate_noise_variance(double value) {
  set_has_rate_noise_variance();
  rate_noise_variance_ = value;
}

// optional double rate_noise_tau = 5;
inline bool ReactionModel_Reaction::has_rate_noise_tau() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ReactionModel_Reaction::set_has_rate_noise_tau() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ReactionModel_Reaction::clear_has_rate_noise_tau() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ReactionModel_Reaction::clear_rate_noise_tau() {
  rate_noise_tau_ = 0;
  clear_has_rate_noise_tau();
}
inline double ReactionModel_Reaction::rate_noise_tau() const {
  return rate_noise_tau_;
}
inline void ReactionModel_Reaction::set_rate_noise_tau(double value) {
  set_has_rate_noise_tau();
  rate_noise_tau_ = value;
}

// -------------------------------------------------------------------

// ReactionModel

// required uint32 number_species = 1;
inline bool ReactionModel::has_number_species() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReactionModel::set_has_number_species() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReactionModel::clear_has_number_species() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReactionModel::clear_number_species() {
  number_species_ = 0u;
  clear_has_number_species();
}
inline ::google::protobuf::uint32 ReactionModel::number_species() const {
  return number_species_;
}
inline void ReactionModel::set_number_species(::google::protobuf::uint32 value) {
  set_has_number_species();
  number_species_ = value;
}

// required uint32 number_reactions = 2;
inline bool ReactionModel::has_number_reactions() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReactionModel::set_has_number_reactions() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReactionModel::clear_has_number_reactions() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReactionModel::clear_number_reactions() {
  number_reactions_ = 0u;
  clear_has_number_reactions();
}
inline ::google::protobuf::uint32 ReactionModel::number_reactions() const {
  return number_reactions_;
}
inline void ReactionModel::set_number_reactions(::google::protobuf::uint32 value) {
  set_has_number_reactions();
  number_reactions_ = value;
}

// repeated uint32 initial_species_count = 3 [packed = true];
inline int ReactionModel::initial_species_count_size() const {
  return initial_species_count_.size();
}
inline void ReactionModel::clear_initial_species_count() {
  initial_species_count_.Clear();
}
inline ::google::protobuf::uint32 ReactionModel::initial_species_count(int index) const {
  return initial_species_count_.Get(index);
}
inline void ReactionModel::set_initial_species_count(int index, ::google::protobuf::uint32 value) {
  initial_species_count_.Set(index, value);
}
inline void ReactionModel::add_initial_species_count(::google::protobuf::uint32 value) {
  initial_species_count_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ReactionModel::initial_species_count() const {
  return initial_species_count_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ReactionModel::mutable_initial_species_count() {
  return &initial_species_count_;
}

// repeated .lm.io.ReactionModel.Reaction reaction = 4;
inline int ReactionModel::reaction_size() const {
  return reaction_.size();
}
inline void ReactionModel::clear_reaction() {
  reaction_.Clear();
}
inline const ::lm::io::ReactionModel_Reaction& ReactionModel::reaction(int index) const {
  return reaction_.Get(index);
}
inline ::lm::io::ReactionModel_Reaction* ReactionModel::mutable_reaction(int index) {
  return reaction_.Mutable(index);
}
inline ::lm::io::ReactionModel_Reaction* ReactionModel::add_reaction() {
  return reaction_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::lm::io::ReactionModel_Reaction >&
ReactionModel::reaction() const {
  return reaction_;
}
inline ::google::protobuf::RepeatedPtrField< ::lm::io::ReactionModel_Reaction >*
ReactionModel::mutable_reaction() {
  return &reaction_;
}

// repeated int32 stoichiometric_matrix = 5 [packed = true];
inline int ReactionModel::stoichiometric_matrix_size() const {
  return stoichiometric_matrix_.size();
}
inline void ReactionModel::clear_stoichiometric_matrix() {
  stoichiometric_matrix_.Clear();
}
inline ::google::protobuf::int32 ReactionModel::stoichiometric_matrix(int index) const {
  return stoichiometric_matrix_.Get(index);
}
inline void ReactionModel::set_stoichiometric_matrix(int index, ::google::protobuf::int32 value) {
  stoichiometric_matrix_.Set(index, value);
}
inline void ReactionModel::add_stoichiometric_matrix(::google::protobuf::int32 value) {
  stoichiometric_matrix_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ReactionModel::stoichiometric_matrix() const {
  return stoichiometric_matrix_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ReactionModel::mutable_stoichiometric_matrix() {
  return &stoichiometric_matrix_;
}

// repeated uint32 dependency_matrix = 6 [packed = true];
inline int ReactionModel::dependency_matrix_size() const {
  return dependency_matrix_.size();
}
inline void ReactionModel::clear_dependency_matrix() {
  dependency_matrix_.Clear();
}
inline ::google::protobuf::uint32 ReactionModel::dependency_matrix(int index) const {
  return dependency_matrix_.Get(index);
}
inline void ReactionModel::set_dependency_matrix(int index, ::google::protobuf::uint32 value) {
  dependency_matrix_.Set(index, value);
}
inline void ReactionModel::add_dependency_matrix(::google::protobuf::uint32 value) {
  dependency_matrix_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ReactionModel::dependency_matrix() const {
  return dependency_matrix_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ReactionModel::mutable_dependency_matrix() {
  return &dependency_matrix_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fio_2fReactionModel_2eproto__INCLUDED
