// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/io/SpatialModel.proto

#ifndef PROTOBUF_lm_2fio_2fSpatialModel_2eproto__INCLUDED
#define PROTOBUF_lm_2fio_2fSpatialModel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto();
void protobuf_AssignDesc_lm_2fio_2fSpatialModel_2eproto();
void protobuf_ShutdownFile_lm_2fio_2fSpatialModel_2eproto();

class SpatialModel;
class SpatialModel_Shape;

// ===================================================================

class SpatialModel_Shape : public ::google::protobuf::Message {
 public:
  SpatialModel_Shape();
  virtual ~SpatialModel_Shape();
  
  SpatialModel_Shape(const SpatialModel_Shape& from);
  
  inline SpatialModel_Shape& operator=(const SpatialModel_Shape& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SpatialModel_Shape& default_instance();
  
  void Swap(SpatialModel_Shape* other);
  
  // implements Message ----------------------------------------------
  
  SpatialModel_Shape* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpatialModel_Shape& from);
  void MergeFrom(const SpatialModel_Shape& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 shape = 1;
  inline bool has_shape() const;
  inline void clear_shape();
  static const int kShapeFieldNumber = 1;
  inline ::google::protobuf::uint32 shape() const;
  inline void set_shape(::google::protobuf::uint32 value);
  
  // required uint32 site_type = 2;
  inline bool has_site_type() const;
  inline void clear_site_type();
  static const int kSiteTypeFieldNumber = 2;
  inline ::google::protobuf::uint32 site_type() const;
  inline void set_site_type(::google::protobuf::uint32 value);
  
  // repeated double shape_parameter = 3 [packed = true];
  inline int shape_parameter_size() const;
  inline void clear_shape_parameter();
  static const int kShapeParameterFieldNumber = 3;
  inline double shape_parameter(int index) const;
  inline void set_shape_parameter(int index, double value);
  inline void add_shape_parameter(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      shape_parameter() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_shape_parameter();
  
  // @@protoc_insertion_point(class_scope:lm.io.SpatialModel.Shape)
 private:
  inline void set_has_shape();
  inline void clear_has_shape();
  inline void set_has_site_type();
  inline void clear_has_site_type();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 shape_;
  ::google::protobuf::uint32 site_type_;
  ::google::protobuf::RepeatedField< double > shape_parameter_;
  mutable int _shape_parameter_cached_byte_size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fSpatialModel_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fSpatialModel_2eproto();
  
  void InitAsDefaultInstance();
  static SpatialModel_Shape* default_instance_;
};
// -------------------------------------------------------------------

class SpatialModel : public ::google::protobuf::Message {
 public:
  SpatialModel();
  virtual ~SpatialModel();
  
  SpatialModel(const SpatialModel& from);
  
  inline SpatialModel& operator=(const SpatialModel& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SpatialModel& default_instance();
  
  void Swap(SpatialModel* other);
  
  // implements Message ----------------------------------------------
  
  SpatialModel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpatialModel& from);
  void MergeFrom(const SpatialModel& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef SpatialModel_Shape Shape;
  
  // accessors -------------------------------------------------------
  
  // repeated .lm.io.SpatialModel.Shape region = 1;
  inline int region_size() const;
  inline void clear_region();
  static const int kRegionFieldNumber = 1;
  inline const ::lm::io::SpatialModel_Shape& region(int index) const;
  inline ::lm::io::SpatialModel_Shape* mutable_region(int index);
  inline ::lm::io::SpatialModel_Shape* add_region();
  inline const ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >&
      region() const;
  inline ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >*
      mutable_region();
  
  // repeated .lm.io.SpatialModel.Shape obstacle = 2;
  inline int obstacle_size() const;
  inline void clear_obstacle();
  static const int kObstacleFieldNumber = 2;
  inline const ::lm::io::SpatialModel_Shape& obstacle(int index) const;
  inline ::lm::io::SpatialModel_Shape* mutable_obstacle(int index);
  inline ::lm::io::SpatialModel_Shape* add_obstacle();
  inline const ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >&
      obstacle() const;
  inline ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >*
      mutable_obstacle();
  
  // @@protoc_insertion_point(class_scope:lm.io.SpatialModel)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape > region_;
  ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape > obstacle_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fSpatialModel_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fSpatialModel_2eproto();
  
  void InitAsDefaultInstance();
  static SpatialModel* default_instance_;
};
// ===================================================================


// ===================================================================

// SpatialModel_Shape

// required uint32 shape = 1;
inline bool SpatialModel_Shape::has_shape() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SpatialModel_Shape::set_has_shape() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SpatialModel_Shape::clear_has_shape() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SpatialModel_Shape::clear_shape() {
  shape_ = 0u;
  clear_has_shape();
}
inline ::google::protobuf::uint32 SpatialModel_Shape::shape() const {
  return shape_;
}
inline void SpatialModel_Shape::set_shape(::google::protobuf::uint32 value) {
  set_has_shape();
  shape_ = value;
}

// required uint32 site_type = 2;
inline bool SpatialModel_Shape::has_site_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SpatialModel_Shape::set_has_site_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SpatialModel_Shape::clear_has_site_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SpatialModel_Shape::clear_site_type() {
  site_type_ = 0u;
  clear_has_site_type();
}
inline ::google::protobuf::uint32 SpatialModel_Shape::site_type() const {
  return site_type_;
}
inline void SpatialModel_Shape::set_site_type(::google::protobuf::uint32 value) {
  set_has_site_type();
  site_type_ = value;
}

// repeated double shape_parameter = 3 [packed = true];
inline int SpatialModel_Shape::shape_parameter_size() const {
  return shape_parameter_.size();
}
inline void SpatialModel_Shape::clear_shape_parameter() {
  shape_parameter_.Clear();
}
inline double SpatialModel_Shape::shape_parameter(int index) const {
  return shape_parameter_.Get(index);
}
inline void SpatialModel_Shape::set_shape_parameter(int index, double value) {
  shape_parameter_.Set(index, value);
}
inline void SpatialModel_Shape::add_shape_parameter(double value) {
  shape_parameter_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
SpatialModel_Shape::shape_parameter() const {
  return shape_parameter_;
}
inline ::google::protobuf::RepeatedField< double >*
SpatialModel_Shape::mutable_shape_parameter() {
  return &shape_parameter_;
}

// -------------------------------------------------------------------

// SpatialModel

// repeated .lm.io.SpatialModel.Shape region = 1;
inline int SpatialModel::region_size() const {
  return region_.size();
}
inline void SpatialModel::clear_region() {
  region_.Clear();
}
inline const ::lm::io::SpatialModel_Shape& SpatialModel::region(int index) const {
  return region_.Get(index);
}
inline ::lm::io::SpatialModel_Shape* SpatialModel::mutable_region(int index) {
  return region_.Mutable(index);
}
inline ::lm::io::SpatialModel_Shape* SpatialModel::add_region() {
  return region_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >&
SpatialModel::region() const {
  return region_;
}
inline ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >*
SpatialModel::mutable_region() {
  return &region_;
}

// repeated .lm.io.SpatialModel.Shape obstacle = 2;
inline int SpatialModel::obstacle_size() const {
  return obstacle_.size();
}
inline void SpatialModel::clear_obstacle() {
  obstacle_.Clear();
}
inline const ::lm::io::SpatialModel_Shape& SpatialModel::obstacle(int index) const {
  return obstacle_.Get(index);
}
inline ::lm::io::SpatialModel_Shape* SpatialModel::mutable_obstacle(int index) {
  return obstacle_.Mutable(index);
}
inline ::lm::io::SpatialModel_Shape* SpatialModel::add_obstacle() {
  return obstacle_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >&
SpatialModel::obstacle() const {
  return obstacle_;
}
inline ::google::protobuf::RepeatedPtrField< ::lm::io::SpatialModel_Shape >*
SpatialModel::mutable_obstacle() {
  return &obstacle_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fio_2fSpatialModel_2eproto__INCLUDED
