// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lm/io/SpatialModel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

namespace {

const ::google::protobuf::Descriptor* SpatialModel_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpatialModel_reflection_ = NULL;
const ::google::protobuf::Descriptor* SpatialModel_Shape_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpatialModel_Shape_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lm_2fio_2fSpatialModel_2eproto() {
  protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lm/io/SpatialModel.proto");
  GOOGLE_CHECK(file != NULL);
  SpatialModel_descriptor_ = file->message_type(0);
  static const int SpatialModel_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel, region_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel, obstacle_),
  };
  SpatialModel_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SpatialModel_descriptor_,
      SpatialModel::default_instance_,
      SpatialModel_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SpatialModel));
  SpatialModel_Shape_descriptor_ = SpatialModel_descriptor_->nested_type(0);
  static const int SpatialModel_Shape_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel_Shape, shape_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel_Shape, site_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel_Shape, shape_parameter_),
  };
  SpatialModel_Shape_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SpatialModel_Shape_descriptor_,
      SpatialModel_Shape::default_instance_,
      SpatialModel_Shape_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel_Shape, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpatialModel_Shape, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SpatialModel_Shape));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lm_2fio_2fSpatialModel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SpatialModel_descriptor_, &SpatialModel::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SpatialModel_Shape_descriptor_, &SpatialModel_Shape::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lm_2fio_2fSpatialModel_2eproto() {
  delete SpatialModel::default_instance_;
  delete SpatialModel_reflection_;
  delete SpatialModel_Shape::default_instance_;
  delete SpatialModel_Shape_reflection_;
}

void protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030lm/io/SpatialModel.proto\022\005lm.io\"\256\001\n\014Sp"
    "atialModel\022)\n\006region\030\001 \003(\0132\031.lm.io.Spati"
    "alModel.Shape\022+\n\010obstacle\030\002 \003(\0132\031.lm.io."
    "SpatialModel.Shape\032F\n\005Shape\022\r\n\005shape\030\001 \002"
    "(\r\022\021\n\tsite_type\030\002 \002(\r\022\033\n\017shape_parameter"
    "\030\003 \003(\001B\002\020\001", 210);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lm/io/SpatialModel.proto", &protobuf_RegisterTypes);
  SpatialModel::default_instance_ = new SpatialModel();
  SpatialModel_Shape::default_instance_ = new SpatialModel_Shape();
  SpatialModel::default_instance_->InitAsDefaultInstance();
  SpatialModel_Shape::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lm_2fio_2fSpatialModel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lm_2fio_2fSpatialModel_2eproto {
  StaticDescriptorInitializer_lm_2fio_2fSpatialModel_2eproto() {
    protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto();
  }
} static_descriptor_initializer_lm_2fio_2fSpatialModel_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SpatialModel_Shape::kShapeFieldNumber;
const int SpatialModel_Shape::kSiteTypeFieldNumber;
const int SpatialModel_Shape::kShapeParameterFieldNumber;
#endif  // !_MSC_VER

SpatialModel_Shape::SpatialModel_Shape()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SpatialModel_Shape::InitAsDefaultInstance() {
}

SpatialModel_Shape::SpatialModel_Shape(const SpatialModel_Shape& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SpatialModel_Shape::SharedCtor() {
  _cached_size_ = 0;
  shape_ = 0u;
  site_type_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SpatialModel_Shape::~SpatialModel_Shape() {
  SharedDtor();
}

void SpatialModel_Shape::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SpatialModel_Shape::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpatialModel_Shape::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpatialModel_Shape_descriptor_;
}

const SpatialModel_Shape& SpatialModel_Shape::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto();  return *default_instance_;
}

SpatialModel_Shape* SpatialModel_Shape::default_instance_ = NULL;

SpatialModel_Shape* SpatialModel_Shape::New() const {
  return new SpatialModel_Shape;
}

void SpatialModel_Shape::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    shape_ = 0u;
    site_type_ = 0u;
  }
  shape_parameter_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SpatialModel_Shape::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 shape = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &shape_)));
          set_has_shape();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_site_type;
        break;
      }
      
      // required uint32 site_type = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_site_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &site_type_)));
          set_has_site_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_shape_parameter;
        break;
      }
      
      // repeated double shape_parameter = 3 [packed = true];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_shape_parameter:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_shape_parameter())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 26, input, this->mutable_shape_parameter())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SpatialModel_Shape::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 shape = 1;
  if (has_shape()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->shape(), output);
  }
  
  // required uint32 site_type = 2;
  if (has_site_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->site_type(), output);
  }
  
  // repeated double shape_parameter = 3 [packed = true];
  if (this->shape_parameter_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_shape_parameter_cached_byte_size_);
  }
  for (int i = 0; i < this->shape_parameter_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->shape_parameter(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SpatialModel_Shape::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 shape = 1;
  if (has_shape()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->shape(), target);
  }
  
  // required uint32 site_type = 2;
  if (has_site_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->site_type(), target);
  }
  
  // repeated double shape_parameter = 3 [packed = true];
  if (this->shape_parameter_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _shape_parameter_cached_byte_size_, target);
  }
  for (int i = 0; i < this->shape_parameter_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->shape_parameter(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SpatialModel_Shape::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 shape = 1;
    if (has_shape()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->shape());
    }
    
    // required uint32 site_type = 2;
    if (has_site_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->site_type());
    }
    
  }
  // repeated double shape_parameter = 3 [packed = true];
  {
    int data_size = 0;
    data_size = 8 * this->shape_parameter_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _shape_parameter_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpatialModel_Shape::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SpatialModel_Shape* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SpatialModel_Shape*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SpatialModel_Shape::MergeFrom(const SpatialModel_Shape& from) {
  GOOGLE_CHECK_NE(&from, this);
  shape_parameter_.MergeFrom(from.shape_parameter_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_shape()) {
      set_shape(from.shape());
    }
    if (from.has_site_type()) {
      set_site_type(from.site_type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SpatialModel_Shape::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpatialModel_Shape::CopyFrom(const SpatialModel_Shape& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpatialModel_Shape::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void SpatialModel_Shape::Swap(SpatialModel_Shape* other) {
  if (other != this) {
    std::swap(shape_, other->shape_);
    std::swap(site_type_, other->site_type_);
    shape_parameter_.Swap(&other->shape_parameter_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SpatialModel_Shape::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpatialModel_Shape_descriptor_;
  metadata.reflection = SpatialModel_Shape_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SpatialModel::kRegionFieldNumber;
const int SpatialModel::kObstacleFieldNumber;
#endif  // !_MSC_VER

SpatialModel::SpatialModel()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SpatialModel::InitAsDefaultInstance() {
}

SpatialModel::SpatialModel(const SpatialModel& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SpatialModel::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SpatialModel::~SpatialModel() {
  SharedDtor();
}

void SpatialModel::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SpatialModel::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpatialModel::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpatialModel_descriptor_;
}

const SpatialModel& SpatialModel::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fio_2fSpatialModel_2eproto();  return *default_instance_;
}

SpatialModel* SpatialModel::default_instance_ = NULL;

SpatialModel* SpatialModel::New() const {
  return new SpatialModel;
}

void SpatialModel::Clear() {
  region_.Clear();
  obstacle_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SpatialModel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .lm.io.SpatialModel.Shape region = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_region:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_region()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_region;
        if (input->ExpectTag(18)) goto parse_obstacle;
        break;
      }
      
      // repeated .lm.io.SpatialModel.Shape obstacle = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_obstacle:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_obstacle()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_obstacle;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SpatialModel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .lm.io.SpatialModel.Shape region = 1;
  for (int i = 0; i < this->region_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->region(i), output);
  }
  
  // repeated .lm.io.SpatialModel.Shape obstacle = 2;
  for (int i = 0; i < this->obstacle_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->obstacle(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SpatialModel::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .lm.io.SpatialModel.Shape region = 1;
  for (int i = 0; i < this->region_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->region(i), target);
  }
  
  // repeated .lm.io.SpatialModel.Shape obstacle = 2;
  for (int i = 0; i < this->obstacle_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->obstacle(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SpatialModel::ByteSize() const {
  int total_size = 0;
  
  // repeated .lm.io.SpatialModel.Shape region = 1;
  total_size += 1 * this->region_size();
  for (int i = 0; i < this->region_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->region(i));
  }
  
  // repeated .lm.io.SpatialModel.Shape obstacle = 2;
  total_size += 1 * this->obstacle_size();
  for (int i = 0; i < this->obstacle_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->obstacle(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpatialModel::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SpatialModel* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SpatialModel*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SpatialModel::MergeFrom(const SpatialModel& from) {
  GOOGLE_CHECK_NE(&from, this);
  region_.MergeFrom(from.region_);
  obstacle_.MergeFrom(from.obstacle_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SpatialModel::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpatialModel::CopyFrom(const SpatialModel& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpatialModel::IsInitialized() const {
  
  for (int i = 0; i < region_size(); i++) {
    if (!this->region(i).IsInitialized()) return false;
  }
  for (int i = 0; i < obstacle_size(); i++) {
    if (!this->obstacle(i).IsInitialized()) return false;
  }
  return true;
}

void SpatialModel::Swap(SpatialModel* other) {
  if (other != this) {
    region_.Swap(&other->region_);
    obstacle_.Swap(&other->obstacle_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SpatialModel::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpatialModel_descriptor_;
  metadata.reflection = SpatialModel_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

// @@protoc_insertion_point(global_scope)
