// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/io/SpeciesCounts.proto

#ifndef PROTOBUF_lm_2fio_2fSpeciesCounts_2eproto__INCLUDED
#define PROTOBUF_lm_2fio_2fSpeciesCounts_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fio_2fSpeciesCounts_2eproto();
void protobuf_AssignDesc_lm_2fio_2fSpeciesCounts_2eproto();
void protobuf_ShutdownFile_lm_2fio_2fSpeciesCounts_2eproto();

class SpeciesCounts;

// ===================================================================

class SpeciesCounts : public ::google::protobuf::Message {
 public:
  SpeciesCounts();
  virtual ~SpeciesCounts();
  
  SpeciesCounts(const SpeciesCounts& from);
  
  inline SpeciesCounts& operator=(const SpeciesCounts& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SpeciesCounts& default_instance();
  
  void Swap(SpeciesCounts* other);
  
  // implements Message ----------------------------------------------
  
  SpeciesCounts* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpeciesCounts& from);
  void MergeFrom(const SpeciesCounts& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 number_species = 1;
  inline bool has_number_species() const;
  inline void clear_number_species();
  static const int kNumberSpeciesFieldNumber = 1;
  inline ::google::protobuf::uint32 number_species() const;
  inline void set_number_species(::google::protobuf::uint32 value);
  
  // required uint32 number_entries = 2;
  inline bool has_number_entries() const;
  inline void clear_number_entries();
  static const int kNumberEntriesFieldNumber = 2;
  inline ::google::protobuf::uint32 number_entries() const;
  inline void set_number_entries(::google::protobuf::uint32 value);
  
  // repeated uint32 species_count = 3 [packed = true];
  inline int species_count_size() const;
  inline void clear_species_count();
  static const int kSpeciesCountFieldNumber = 3;
  inline ::google::protobuf::uint32 species_count(int index) const;
  inline void set_species_count(int index, ::google::protobuf::uint32 value);
  inline void add_species_count(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      species_count() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_species_count();
  
  // repeated double time = 4 [packed = true];
  inline int time_size() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 4;
  inline double time(int index) const;
  inline void set_time(int index, double value);
  inline void add_time(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      time() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_time();
  
  // @@protoc_insertion_point(class_scope:lm.io.SpeciesCounts)
 private:
  inline void set_has_number_species();
  inline void clear_has_number_species();
  inline void set_has_number_entries();
  inline void clear_has_number_entries();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 number_species_;
  ::google::protobuf::uint32 number_entries_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > species_count_;
  mutable int _species_count_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > time_;
  mutable int _time_cached_byte_size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fSpeciesCounts_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fSpeciesCounts_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fSpeciesCounts_2eproto();
  
  void InitAsDefaultInstance();
  static SpeciesCounts* default_instance_;
};
// ===================================================================


// ===================================================================

// SpeciesCounts

// required uint32 number_species = 1;
inline bool SpeciesCounts::has_number_species() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SpeciesCounts::set_has_number_species() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SpeciesCounts::clear_has_number_species() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SpeciesCounts::clear_number_species() {
  number_species_ = 0u;
  clear_has_number_species();
}
inline ::google::protobuf::uint32 SpeciesCounts::number_species() const {
  return number_species_;
}
inline void SpeciesCounts::set_number_species(::google::protobuf::uint32 value) {
  set_has_number_species();
  number_species_ = value;
}

// required uint32 number_entries = 2;
inline bool SpeciesCounts::has_number_entries() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SpeciesCounts::set_has_number_entries() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SpeciesCounts::clear_has_number_entries() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SpeciesCounts::clear_number_entries() {
  number_entries_ = 0u;
  clear_has_number_entries();
}
inline ::google::protobuf::uint32 SpeciesCounts::number_entries() const {
  return number_entries_;
}
inline void SpeciesCounts::set_number_entries(::google::protobuf::uint32 value) {
  set_has_number_entries();
  number_entries_ = value;
}

// repeated uint32 species_count = 3 [packed = true];
inline int SpeciesCounts::species_count_size() const {
  return species_count_.size();
}
inline void SpeciesCounts::clear_species_count() {
  species_count_.Clear();
}
inline ::google::protobuf::uint32 SpeciesCounts::species_count(int index) const {
  return species_count_.Get(index);
}
inline void SpeciesCounts::set_species_count(int index, ::google::protobuf::uint32 value) {
  species_count_.Set(index, value);
}
inline void SpeciesCounts::add_species_count(::google::protobuf::uint32 value) {
  species_count_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SpeciesCounts::species_count() const {
  return species_count_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SpeciesCounts::mutable_species_count() {
  return &species_count_;
}

// repeated double time = 4 [packed = true];
inline int SpeciesCounts::time_size() const {
  return time_.size();
}
inline void SpeciesCounts::clear_time() {
  time_.Clear();
}
inline double SpeciesCounts::time(int index) const {
  return time_.Get(index);
}
inline void SpeciesCounts::set_time(int index, double value) {
  time_.Set(index, value);
}
inline void SpeciesCounts::add_time(double value) {
  time_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
SpeciesCounts::time() const {
  return time_;
}
inline ::google::protobuf::RepeatedField< double >*
SpeciesCounts::mutable_time() {
  return &time_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fio_2fSpeciesCounts_2eproto__INCLUDED
