// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lm/message/SimulationParameters.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace message {

namespace {

const ::google::protobuf::Descriptor* SimulationParameters_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SimulationParameters_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lm_2fmessage_2fSimulationParameters_2eproto() {
  protobuf_AddDesc_lm_2fmessage_2fSimulationParameters_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lm/message/SimulationParameters.proto");
  GOOGLE_CHECK(file != NULL);
  SimulationParameters_descriptor_ = file->message_type(0);
  static const int SimulationParameters_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimulationParameters, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimulationParameters, value_),
  };
  SimulationParameters_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SimulationParameters_descriptor_,
      SimulationParameters::default_instance_,
      SimulationParameters_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimulationParameters, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimulationParameters, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SimulationParameters));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lm_2fmessage_2fSimulationParameters_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SimulationParameters_descriptor_, &SimulationParameters::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lm_2fmessage_2fSimulationParameters_2eproto() {
  delete SimulationParameters::default_instance_;
  delete SimulationParameters_reflection_;
}

void protobuf_AddDesc_lm_2fmessage_2fSimulationParameters_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n%lm/message/SimulationParameters.proto\022"
    "\nlm.message\"2\n\024SimulationParameters\022\013\n\003k"
    "ey\030\001 \003(\t\022\r\n\005value\030\002 \003(\t", 103);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lm/message/SimulationParameters.proto", &protobuf_RegisterTypes);
  SimulationParameters::default_instance_ = new SimulationParameters();
  SimulationParameters::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lm_2fmessage_2fSimulationParameters_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lm_2fmessage_2fSimulationParameters_2eproto {
  StaticDescriptorInitializer_lm_2fmessage_2fSimulationParameters_2eproto() {
    protobuf_AddDesc_lm_2fmessage_2fSimulationParameters_2eproto();
  }
} static_descriptor_initializer_lm_2fmessage_2fSimulationParameters_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SimulationParameters::kKeyFieldNumber;
const int SimulationParameters::kValueFieldNumber;
#endif  // !_MSC_VER

SimulationParameters::SimulationParameters()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SimulationParameters::InitAsDefaultInstance() {
}

SimulationParameters::SimulationParameters(const SimulationParameters& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SimulationParameters::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SimulationParameters::~SimulationParameters() {
  SharedDtor();
}

void SimulationParameters::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SimulationParameters::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SimulationParameters::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SimulationParameters_descriptor_;
}

const SimulationParameters& SimulationParameters::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fmessage_2fSimulationParameters_2eproto();  return *default_instance_;
}

SimulationParameters* SimulationParameters::default_instance_ = NULL;

SimulationParameters* SimulationParameters::New() const {
  return new SimulationParameters;
}

void SimulationParameters::Clear() {
  key_.Clear();
  value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SimulationParameters::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_key:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->key(0).data(), this->key(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_key;
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }
      
      // repeated string value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->value(0).data(), this->value(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SimulationParameters::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string key = 1;
  for (int i = 0; i < this->key_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->key(i).data(), this->key(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->key(i), output);
  }
  
  // repeated string value = 2;
  for (int i = 0; i < this->value_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->value(i).data(), this->value(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->value(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SimulationParameters::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string key = 1;
  for (int i = 0; i < this->key_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->key(i).data(), this->key(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->key(i), target);
  }
  
  // repeated string value = 2;
  for (int i = 0; i < this->value_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value(i).data(), this->value(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->value(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SimulationParameters::ByteSize() const {
  int total_size = 0;
  
  // repeated string key = 1;
  total_size += 1 * this->key_size();
  for (int i = 0; i < this->key_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->key(i));
  }
  
  // repeated string value = 2;
  total_size += 1 * this->value_size();
  for (int i = 0; i < this->value_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->value(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SimulationParameters::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SimulationParameters* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SimulationParameters*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SimulationParameters::MergeFrom(const SimulationParameters& from) {
  GOOGLE_CHECK_NE(&from, this);
  key_.MergeFrom(from.key_);
  value_.MergeFrom(from.value_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SimulationParameters::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SimulationParameters::CopyFrom(const SimulationParameters& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimulationParameters::IsInitialized() const {
  
  return true;
}

void SimulationParameters::Swap(SimulationParameters* other) {
  if (other != this) {
    key_.Swap(&other->key_);
    value_.Swap(&other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SimulationParameters::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SimulationParameters_descriptor_;
  metadata.reflection = SimulationParameters_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace lm

// @@protoc_insertion_point(global_scope)
