import "ReadWrite.proto";

package lm.work;

message Result {
	optional uint32 tid		 			= 1;
	optional uint32 pid					= 2;
	optional uint32 sid					= 3;
		
	enum JobType {
		REPLICATE = 0;
		FFS1 = 1;
		FFS2 = 2;
	}
	
	enum SolverType {
		CME = 0;
		RDME = 1;
	}
	
	optional JobType jobType			= 4;
	optional SolverType solverType		= 5;
	optional uint32 ffs2Interface		= 6;
	repeated lm.work.ReadWrite readWrite	= 7;
	repeated uint32 writeIndexes		= 8 [packed=true];	//the indexes (if any) of this message's readWrite array that should be written out to disk
}