import "lm/work/ReadOnly.proto";
import "lm/work/ReadWrite.proto";

package lm.work;

message Work {
	optional uint32 tid 				= 1;
	optional uint32 pid					= 2;
	optional uint32 sid					= 3;
	
	enum JobType {
		REPLICATE = 0;
		FFS1 = 1;
		FFS2 = 2;
	}
	
	enum SolverType {
		CME = 0;
		RDME = 1;
	}
	
	optional JobType jobType			= 4;
	optional SolverType solverType		= 5;
	optional uint32 ffs2Interface		= 6;
	optional double wallClockTime		= 7;
	optional lm.work.ReadOnly readOnly 	= 8;
	optional lm.work.ReadWrite readWrite	= 9;
}