// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/io/DiffusionModel.proto

#ifndef PROTOBUF_lm_2fio_2fDiffusionModel_2eproto__INCLUDED
#define PROTOBUF_lm_2fio_2fDiffusionModel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fio_2fDiffusionModel_2eproto();
void protobuf_AssignDesc_lm_2fio_2fDiffusionModel_2eproto();
void protobuf_ShutdownFile_lm_2fio_2fDiffusionModel_2eproto();

class DiffusionModel;

// ===================================================================

class DiffusionModel : public ::google::protobuf::Message {
 public:
  DiffusionModel();
  virtual ~DiffusionModel();
  
  DiffusionModel(const DiffusionModel& from);
  
  inline DiffusionModel& operator=(const DiffusionModel& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DiffusionModel& default_instance();
  
  void Swap(DiffusionModel* other);
  
  // implements Message ----------------------------------------------
  
  DiffusionModel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DiffusionModel& from);
  void MergeFrom(const DiffusionModel& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 number_species = 1;
  inline bool has_number_species() const;
  inline void clear_number_species();
  static const int kNumberSpeciesFieldNumber = 1;
  inline ::google::protobuf::uint32 number_species() const;
  inline void set_number_species(::google::protobuf::uint32 value);
  
  // required uint32 number_reactions = 2;
  inline bool has_number_reactions() const;
  inline void clear_number_reactions();
  static const int kNumberReactionsFieldNumber = 2;
  inline ::google::protobuf::uint32 number_reactions() const;
  inline void set_number_reactions(::google::protobuf::uint32 value);
  
  // required uint32 number_site_types = 3;
  inline bool has_number_site_types() const;
  inline void clear_number_site_types();
  static const int kNumberSiteTypesFieldNumber = 3;
  inline ::google::protobuf::uint32 number_site_types() const;
  inline void set_number_site_types(::google::protobuf::uint32 value);
  
  // repeated double diffusion_matrix = 4 [packed = true];
  inline int diffusion_matrix_size() const;
  inline void clear_diffusion_matrix();
  static const int kDiffusionMatrixFieldNumber = 4;
  inline double diffusion_matrix(int index) const;
  inline void set_diffusion_matrix(int index, double value);
  inline void add_diffusion_matrix(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      diffusion_matrix() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_diffusion_matrix();
  
  // repeated uint32 reaction_location_matrix = 5 [packed = true];
  inline int reaction_location_matrix_size() const;
  inline void clear_reaction_location_matrix();
  static const int kReactionLocationMatrixFieldNumber = 5;
  inline ::google::protobuf::uint32 reaction_location_matrix(int index) const;
  inline void set_reaction_location_matrix(int index, ::google::protobuf::uint32 value);
  inline void add_reaction_location_matrix(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      reaction_location_matrix() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_reaction_location_matrix();
  
  // required double lattice_spacing = 6;
  inline bool has_lattice_spacing() const;
  inline void clear_lattice_spacing();
  static const int kLatticeSpacingFieldNumber = 6;
  inline double lattice_spacing() const;
  inline void set_lattice_spacing(double value);
  
  // required uint32 lattice_x_size = 7;
  inline bool has_lattice_x_size() const;
  inline void clear_lattice_x_size();
  static const int kLatticeXSizeFieldNumber = 7;
  inline ::google::protobuf::uint32 lattice_x_size() const;
  inline void set_lattice_x_size(::google::protobuf::uint32 value);
  
  // required uint32 lattice_y_size = 8;
  inline bool has_lattice_y_size() const;
  inline void clear_lattice_y_size();
  static const int kLatticeYSizeFieldNumber = 8;
  inline ::google::protobuf::uint32 lattice_y_size() const;
  inline void set_lattice_y_size(::google::protobuf::uint32 value);
  
  // required uint32 lattice_z_size = 9;
  inline bool has_lattice_z_size() const;
  inline void clear_lattice_z_size();
  static const int kLatticeZSizeFieldNumber = 9;
  inline ::google::protobuf::uint32 lattice_z_size() const;
  inline void set_lattice_z_size(::google::protobuf::uint32 value);
  
  // required uint32 particles_per_site = 10;
  inline bool has_particles_per_site() const;
  inline void clear_particles_per_site();
  static const int kParticlesPerSiteFieldNumber = 10;
  inline ::google::protobuf::uint32 particles_per_site() const;
  inline void set_particles_per_site(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:lm.io.DiffusionModel)
 private:
  inline void set_has_number_species();
  inline void clear_has_number_species();
  inline void set_has_number_reactions();
  inline void clear_has_number_reactions();
  inline void set_has_number_site_types();
  inline void clear_has_number_site_types();
  inline void set_has_lattice_spacing();
  inline void clear_has_lattice_spacing();
  inline void set_has_lattice_x_size();
  inline void clear_has_lattice_x_size();
  inline void set_has_lattice_y_size();
  inline void clear_has_lattice_y_size();
  inline void set_has_lattice_z_size();
  inline void clear_has_lattice_z_size();
  inline void set_has_particles_per_site();
  inline void clear_has_particles_per_site();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 number_species_;
  ::google::protobuf::uint32 number_reactions_;
  ::google::protobuf::RepeatedField< double > diffusion_matrix_;
  mutable int _diffusion_matrix_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > reaction_location_matrix_;
  mutable int _reaction_location_matrix_cached_byte_size_;
  ::google::protobuf::uint32 number_site_types_;
  ::google::protobuf::uint32 lattice_x_size_;
  double lattice_spacing_;
  ::google::protobuf::uint32 lattice_y_size_;
  ::google::protobuf::uint32 lattice_z_size_;
  ::google::protobuf::uint32 particles_per_site_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fio_2fDiffusionModel_2eproto();
  friend void protobuf_AssignDesc_lm_2fio_2fDiffusionModel_2eproto();
  friend void protobuf_ShutdownFile_lm_2fio_2fDiffusionModel_2eproto();
  
  void InitAsDefaultInstance();
  static DiffusionModel* default_instance_;
};
// ===================================================================


// ===================================================================

// DiffusionModel

// required uint32 number_species = 1;
inline bool DiffusionModel::has_number_species() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DiffusionModel::set_has_number_species() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DiffusionModel::clear_has_number_species() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DiffusionModel::clear_number_species() {
  number_species_ = 0u;
  clear_has_number_species();
}
inline ::google::protobuf::uint32 DiffusionModel::number_species() const {
  return number_species_;
}
inline void DiffusionModel::set_number_species(::google::protobuf::uint32 value) {
  set_has_number_species();
  number_species_ = value;
}

// required uint32 number_reactions = 2;
inline bool DiffusionModel::has_number_reactions() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DiffusionModel::set_has_number_reactions() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DiffusionModel::clear_has_number_reactions() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DiffusionModel::clear_number_reactions() {
  number_reactions_ = 0u;
  clear_has_number_reactions();
}
inline ::google::protobuf::uint32 DiffusionModel::number_reactions() const {
  return number_reactions_;
}
inline void DiffusionModel::set_number_reactions(::google::protobuf::uint32 value) {
  set_has_number_reactions();
  number_reactions_ = value;
}

// required uint32 number_site_types = 3;
inline bool DiffusionModel::has_number_site_types() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DiffusionModel::set_has_number_site_types() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DiffusionModel::clear_has_number_site_types() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DiffusionModel::clear_number_site_types() {
  number_site_types_ = 0u;
  clear_has_number_site_types();
}
inline ::google::protobuf::uint32 DiffusionModel::number_site_types() const {
  return number_site_types_;
}
inline void DiffusionModel::set_number_site_types(::google::protobuf::uint32 value) {
  set_has_number_site_types();
  number_site_types_ = value;
}

// repeated double diffusion_matrix = 4 [packed = true];
inline int DiffusionModel::diffusion_matrix_size() const {
  return diffusion_matrix_.size();
}
inline void DiffusionModel::clear_diffusion_matrix() {
  diffusion_matrix_.Clear();
}
inline double DiffusionModel::diffusion_matrix(int index) const {
  return diffusion_matrix_.Get(index);
}
inline void DiffusionModel::set_diffusion_matrix(int index, double value) {
  diffusion_matrix_.Set(index, value);
}
inline void DiffusionModel::add_diffusion_matrix(double value) {
  diffusion_matrix_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
DiffusionModel::diffusion_matrix() const {
  return diffusion_matrix_;
}
inline ::google::protobuf::RepeatedField< double >*
DiffusionModel::mutable_diffusion_matrix() {
  return &diffusion_matrix_;
}

// repeated uint32 reaction_location_matrix = 5 [packed = true];
inline int DiffusionModel::reaction_location_matrix_size() const {
  return reaction_location_matrix_.size();
}
inline void DiffusionModel::clear_reaction_location_matrix() {
  reaction_location_matrix_.Clear();
}
inline ::google::protobuf::uint32 DiffusionModel::reaction_location_matrix(int index) const {
  return reaction_location_matrix_.Get(index);
}
inline void DiffusionModel::set_reaction_location_matrix(int index, ::google::protobuf::uint32 value) {
  reaction_location_matrix_.Set(index, value);
}
inline void DiffusionModel::add_reaction_location_matrix(::google::protobuf::uint32 value) {
  reaction_location_matrix_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
DiffusionModel::reaction_location_matrix() const {
  return reaction_location_matrix_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
DiffusionModel::mutable_reaction_location_matrix() {
  return &reaction_location_matrix_;
}

// required double lattice_spacing = 6;
inline bool DiffusionModel::has_lattice_spacing() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DiffusionModel::set_has_lattice_spacing() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DiffusionModel::clear_has_lattice_spacing() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DiffusionModel::clear_lattice_spacing() {
  lattice_spacing_ = 0;
  clear_has_lattice_spacing();
}
inline double DiffusionModel::lattice_spacing() const {
  return lattice_spacing_;
}
inline void DiffusionModel::set_lattice_spacing(double value) {
  set_has_lattice_spacing();
  lattice_spacing_ = value;
}

// required uint32 lattice_x_size = 7;
inline bool DiffusionModel::has_lattice_x_size() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void DiffusionModel::set_has_lattice_x_size() {
  _has_bits_[0] |= 0x00000040u;
}
inline void DiffusionModel::clear_has_lattice_x_size() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void DiffusionModel::clear_lattice_x_size() {
  lattice_x_size_ = 0u;
  clear_has_lattice_x_size();
}
inline ::google::protobuf::uint32 DiffusionModel::lattice_x_size() const {
  return lattice_x_size_;
}
inline void DiffusionModel::set_lattice_x_size(::google::protobuf::uint32 value) {
  set_has_lattice_x_size();
  lattice_x_size_ = value;
}

// required uint32 lattice_y_size = 8;
inline bool DiffusionModel::has_lattice_y_size() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void DiffusionModel::set_has_lattice_y_size() {
  _has_bits_[0] |= 0x00000080u;
}
inline void DiffusionModel::clear_has_lattice_y_size() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void DiffusionModel::clear_lattice_y_size() {
  lattice_y_size_ = 0u;
  clear_has_lattice_y_size();
}
inline ::google::protobuf::uint32 DiffusionModel::lattice_y_size() const {
  return lattice_y_size_;
}
inline void DiffusionModel::set_lattice_y_size(::google::protobuf::uint32 value) {
  set_has_lattice_y_size();
  lattice_y_size_ = value;
}

// required uint32 lattice_z_size = 9;
inline bool DiffusionModel::has_lattice_z_size() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void DiffusionModel::set_has_lattice_z_size() {
  _has_bits_[0] |= 0x00000100u;
}
inline void DiffusionModel::clear_has_lattice_z_size() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void DiffusionModel::clear_lattice_z_size() {
  lattice_z_size_ = 0u;
  clear_has_lattice_z_size();
}
inline ::google::protobuf::uint32 DiffusionModel::lattice_z_size() const {
  return lattice_z_size_;
}
inline void DiffusionModel::set_lattice_z_size(::google::protobuf::uint32 value) {
  set_has_lattice_z_size();
  lattice_z_size_ = value;
}

// required uint32 particles_per_site = 10;
inline bool DiffusionModel::has_particles_per_site() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void DiffusionModel::set_has_particles_per_site() {
  _has_bits_[0] |= 0x00000200u;
}
inline void DiffusionModel::clear_has_particles_per_site() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void DiffusionModel::clear_particles_per_site() {
  particles_per_site_ = 0u;
  clear_has_particles_per_site();
}
inline ::google::protobuf::uint32 DiffusionModel::particles_per_site() const {
  return particles_per_site_;
}
inline void DiffusionModel::set_particles_per_site(::google::protobuf::uint32 value) {
  set_has_particles_per_site();
  particles_per_site_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fio_2fDiffusionModel_2eproto__INCLUDED
