// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lm/io/DiffusionModel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

namespace {

const ::google::protobuf::Descriptor* DiffusionModel_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DiffusionModel_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lm_2fio_2fDiffusionModel_2eproto() {
  protobuf_AddDesc_lm_2fio_2fDiffusionModel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lm/io/DiffusionModel.proto");
  GOOGLE_CHECK(file != NULL);
  DiffusionModel_descriptor_ = file->message_type(0);
  static const int DiffusionModel_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, number_species_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, number_reactions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, number_site_types_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, diffusion_matrix_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, reaction_location_matrix_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, lattice_spacing_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, lattice_x_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, lattice_y_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, lattice_z_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, particles_per_site_),
  };
  DiffusionModel_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DiffusionModel_descriptor_,
      DiffusionModel::default_instance_,
      DiffusionModel_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffusionModel, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DiffusionModel));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lm_2fio_2fDiffusionModel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DiffusionModel_descriptor_, &DiffusionModel::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lm_2fio_2fDiffusionModel_2eproto() {
  delete DiffusionModel::default_instance_;
  delete DiffusionModel_reflection_;
}

void protobuf_AddDesc_lm_2fio_2fDiffusionModel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032lm/io/DiffusionModel.proto\022\005lm.io\"\236\002\n\016"
    "DiffusionModel\022\026\n\016number_species\030\001 \002(\r\022\030"
    "\n\020number_reactions\030\002 \002(\r\022\031\n\021number_site_"
    "types\030\003 \002(\r\022\034\n\020diffusion_matrix\030\004 \003(\001B\002\020"
    "\001\022$\n\030reaction_location_matrix\030\005 \003(\rB\002\020\001\022"
    "\027\n\017lattice_spacing\030\006 \002(\001\022\026\n\016lattice_x_si"
    "ze\030\007 \002(\r\022\026\n\016lattice_y_size\030\010 \002(\r\022\026\n\016latt"
    "ice_z_size\030\t \002(\r\022\032\n\022particles_per_site\030\n"
    " \002(\r", 324);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lm/io/DiffusionModel.proto", &protobuf_RegisterTypes);
  DiffusionModel::default_instance_ = new DiffusionModel();
  DiffusionModel::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lm_2fio_2fDiffusionModel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lm_2fio_2fDiffusionModel_2eproto {
  StaticDescriptorInitializer_lm_2fio_2fDiffusionModel_2eproto() {
    protobuf_AddDesc_lm_2fio_2fDiffusionModel_2eproto();
  }
} static_descriptor_initializer_lm_2fio_2fDiffusionModel_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int DiffusionModel::kNumberSpeciesFieldNumber;
const int DiffusionModel::kNumberReactionsFieldNumber;
const int DiffusionModel::kNumberSiteTypesFieldNumber;
const int DiffusionModel::kDiffusionMatrixFieldNumber;
const int DiffusionModel::kReactionLocationMatrixFieldNumber;
const int DiffusionModel::kLatticeSpacingFieldNumber;
const int DiffusionModel::kLatticeXSizeFieldNumber;
const int DiffusionModel::kLatticeYSizeFieldNumber;
const int DiffusionModel::kLatticeZSizeFieldNumber;
const int DiffusionModel::kParticlesPerSiteFieldNumber;
#endif  // !_MSC_VER

DiffusionModel::DiffusionModel()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DiffusionModel::InitAsDefaultInstance() {
}

DiffusionModel::DiffusionModel(const DiffusionModel& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DiffusionModel::SharedCtor() {
  _cached_size_ = 0;
  number_species_ = 0u;
  number_reactions_ = 0u;
  number_site_types_ = 0u;
  lattice_spacing_ = 0;
  lattice_x_size_ = 0u;
  lattice_y_size_ = 0u;
  lattice_z_size_ = 0u;
  particles_per_site_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DiffusionModel::~DiffusionModel() {
  SharedDtor();
}

void DiffusionModel::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DiffusionModel::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DiffusionModel::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DiffusionModel_descriptor_;
}

const DiffusionModel& DiffusionModel::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fio_2fDiffusionModel_2eproto();  return *default_instance_;
}

DiffusionModel* DiffusionModel::default_instance_ = NULL;

DiffusionModel* DiffusionModel::New() const {
  return new DiffusionModel;
}

void DiffusionModel::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    number_species_ = 0u;
    number_reactions_ = 0u;
    number_site_types_ = 0u;
    lattice_spacing_ = 0;
    lattice_x_size_ = 0u;
    lattice_y_size_ = 0u;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    lattice_z_size_ = 0u;
    particles_per_site_ = 0u;
  }
  diffusion_matrix_.Clear();
  reaction_location_matrix_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DiffusionModel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 number_species = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_species_)));
          set_has_number_species();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_number_reactions;
        break;
      }
      
      // required uint32 number_reactions = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_number_reactions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_reactions_)));
          set_has_number_reactions();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_number_site_types;
        break;
      }
      
      // required uint32 number_site_types = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_number_site_types:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_site_types_)));
          set_has_number_site_types();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_diffusion_matrix;
        break;
      }
      
      // repeated double diffusion_matrix = 4 [packed = true];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_diffusion_matrix:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_diffusion_matrix())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 34, input, this->mutable_diffusion_matrix())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_reaction_location_matrix;
        break;
      }
      
      // repeated uint32 reaction_location_matrix = 5 [packed = true];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_reaction_location_matrix:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_reaction_location_matrix())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 42, input, this->mutable_reaction_location_matrix())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(49)) goto parse_lattice_spacing;
        break;
      }
      
      // required double lattice_spacing = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_lattice_spacing:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lattice_spacing_)));
          set_has_lattice_spacing();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_lattice_x_size;
        break;
      }
      
      // required uint32 lattice_x_size = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_lattice_x_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &lattice_x_size_)));
          set_has_lattice_x_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_lattice_y_size;
        break;
      }
      
      // required uint32 lattice_y_size = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_lattice_y_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &lattice_y_size_)));
          set_has_lattice_y_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_lattice_z_size;
        break;
      }
      
      // required uint32 lattice_z_size = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_lattice_z_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &lattice_z_size_)));
          set_has_lattice_z_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_particles_per_site;
        break;
      }
      
      // required uint32 particles_per_site = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_particles_per_site:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &particles_per_site_)));
          set_has_particles_per_site();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DiffusionModel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 number_species = 1;
  if (has_number_species()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->number_species(), output);
  }
  
  // required uint32 number_reactions = 2;
  if (has_number_reactions()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->number_reactions(), output);
  }
  
  // required uint32 number_site_types = 3;
  if (has_number_site_types()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->number_site_types(), output);
  }
  
  // repeated double diffusion_matrix = 4 [packed = true];
  if (this->diffusion_matrix_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_diffusion_matrix_cached_byte_size_);
  }
  for (int i = 0; i < this->diffusion_matrix_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->diffusion_matrix(i), output);
  }
  
  // repeated uint32 reaction_location_matrix = 5 [packed = true];
  if (this->reaction_location_matrix_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_reaction_location_matrix_cached_byte_size_);
  }
  for (int i = 0; i < this->reaction_location_matrix_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->reaction_location_matrix(i), output);
  }
  
  // required double lattice_spacing = 6;
  if (has_lattice_spacing()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->lattice_spacing(), output);
  }
  
  // required uint32 lattice_x_size = 7;
  if (has_lattice_x_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->lattice_x_size(), output);
  }
  
  // required uint32 lattice_y_size = 8;
  if (has_lattice_y_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->lattice_y_size(), output);
  }
  
  // required uint32 lattice_z_size = 9;
  if (has_lattice_z_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->lattice_z_size(), output);
  }
  
  // required uint32 particles_per_site = 10;
  if (has_particles_per_site()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->particles_per_site(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DiffusionModel::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 number_species = 1;
  if (has_number_species()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->number_species(), target);
  }
  
  // required uint32 number_reactions = 2;
  if (has_number_reactions()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->number_reactions(), target);
  }
  
  // required uint32 number_site_types = 3;
  if (has_number_site_types()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->number_site_types(), target);
  }
  
  // repeated double diffusion_matrix = 4 [packed = true];
  if (this->diffusion_matrix_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _diffusion_matrix_cached_byte_size_, target);
  }
  for (int i = 0; i < this->diffusion_matrix_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->diffusion_matrix(i), target);
  }
  
  // repeated uint32 reaction_location_matrix = 5 [packed = true];
  if (this->reaction_location_matrix_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _reaction_location_matrix_cached_byte_size_, target);
  }
  for (int i = 0; i < this->reaction_location_matrix_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->reaction_location_matrix(i), target);
  }
  
  // required double lattice_spacing = 6;
  if (has_lattice_spacing()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->lattice_spacing(), target);
  }
  
  // required uint32 lattice_x_size = 7;
  if (has_lattice_x_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->lattice_x_size(), target);
  }
  
  // required uint32 lattice_y_size = 8;
  if (has_lattice_y_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->lattice_y_size(), target);
  }
  
  // required uint32 lattice_z_size = 9;
  if (has_lattice_z_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->lattice_z_size(), target);
  }
  
  // required uint32 particles_per_site = 10;
  if (has_particles_per_site()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->particles_per_site(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DiffusionModel::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 number_species = 1;
    if (has_number_species()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->number_species());
    }
    
    // required uint32 number_reactions = 2;
    if (has_number_reactions()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->number_reactions());
    }
    
    // required uint32 number_site_types = 3;
    if (has_number_site_types()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->number_site_types());
    }
    
    // required double lattice_spacing = 6;
    if (has_lattice_spacing()) {
      total_size += 1 + 8;
    }
    
    // required uint32 lattice_x_size = 7;
    if (has_lattice_x_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->lattice_x_size());
    }
    
    // required uint32 lattice_y_size = 8;
    if (has_lattice_y_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->lattice_y_size());
    }
    
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required uint32 lattice_z_size = 9;
    if (has_lattice_z_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->lattice_z_size());
    }
    
    // required uint32 particles_per_site = 10;
    if (has_particles_per_site()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->particles_per_site());
    }
    
  }
  // repeated double diffusion_matrix = 4 [packed = true];
  {
    int data_size = 0;
    data_size = 8 * this->diffusion_matrix_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _diffusion_matrix_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  // repeated uint32 reaction_location_matrix = 5 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->reaction_location_matrix_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->reaction_location_matrix(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _reaction_location_matrix_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DiffusionModel::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DiffusionModel* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DiffusionModel*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DiffusionModel::MergeFrom(const DiffusionModel& from) {
  GOOGLE_CHECK_NE(&from, this);
  diffusion_matrix_.MergeFrom(from.diffusion_matrix_);
  reaction_location_matrix_.MergeFrom(from.reaction_location_matrix_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_number_species()) {
      set_number_species(from.number_species());
    }
    if (from.has_number_reactions()) {
      set_number_reactions(from.number_reactions());
    }
    if (from.has_number_site_types()) {
      set_number_site_types(from.number_site_types());
    }
    if (from.has_lattice_spacing()) {
      set_lattice_spacing(from.lattice_spacing());
    }
    if (from.has_lattice_x_size()) {
      set_lattice_x_size(from.lattice_x_size());
    }
    if (from.has_lattice_y_size()) {
      set_lattice_y_size(from.lattice_y_size());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_lattice_z_size()) {
      set_lattice_z_size(from.lattice_z_size());
    }
    if (from.has_particles_per_site()) {
      set_particles_per_site(from.particles_per_site());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DiffusionModel::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DiffusionModel::CopyFrom(const DiffusionModel& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiffusionModel::IsInitialized() const {
  if ((_has_bits_[0] & 0x000003e7) != 0x000003e7) return false;
  
  return true;
}

void DiffusionModel::Swap(DiffusionModel* other) {
  if (other != this) {
    std::swap(number_species_, other->number_species_);
    std::swap(number_reactions_, other->number_reactions_);
    std::swap(number_site_types_, other->number_site_types_);
    diffusion_matrix_.Swap(&other->diffusion_matrix_);
    reaction_location_matrix_.Swap(&other->reaction_location_matrix_);
    std::swap(lattice_spacing_, other->lattice_spacing_);
    std::swap(lattice_x_size_, other->lattice_x_size_);
    std::swap(lattice_y_size_, other->lattice_y_size_);
    std::swap(lattice_z_size_, other->lattice_z_size_);
    std::swap(particles_per_site_, other->particles_per_site_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DiffusionModel::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DiffusionModel_descriptor_;
  metadata.reflection = DiffusionModel_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

// @@protoc_insertion_point(global_scope)
