// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lm/io/FirstPassageTimes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

namespace {

const ::google::protobuf::Descriptor* FirstPassageTimes_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FirstPassageTimes_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lm_2fio_2fFirstPassageTimes_2eproto() {
  protobuf_AddDesc_lm_2fio_2fFirstPassageTimes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lm/io/FirstPassageTimes.proto");
  GOOGLE_CHECK(file != NULL);
  FirstPassageTimes_descriptor_ = file->message_type(0);
  static const int FirstPassageTimes_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FirstPassageTimes, species_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FirstPassageTimes, species_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FirstPassageTimes, first_passage_time_),
  };
  FirstPassageTimes_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FirstPassageTimes_descriptor_,
      FirstPassageTimes::default_instance_,
      FirstPassageTimes_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FirstPassageTimes, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FirstPassageTimes, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FirstPassageTimes));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lm_2fio_2fFirstPassageTimes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FirstPassageTimes_descriptor_, &FirstPassageTimes::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lm_2fio_2fFirstPassageTimes_2eproto() {
  delete FirstPassageTimes::default_instance_;
  delete FirstPassageTimes_reflection_;
}

void protobuf_AddDesc_lm_2fio_2fFirstPassageTimes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035lm/io/FirstPassageTimes.proto\022\005lm.io\"_"
    "\n\021FirstPassageTimes\022\017\n\007species\030\001 \002(\r\022\031\n\r"
    "species_count\030\002 \003(\rB\002\020\001\022\036\n\022first_passage"
    "_time\030\003 \003(\001B\002\020\001", 135);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lm/io/FirstPassageTimes.proto", &protobuf_RegisterTypes);
  FirstPassageTimes::default_instance_ = new FirstPassageTimes();
  FirstPassageTimes::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lm_2fio_2fFirstPassageTimes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lm_2fio_2fFirstPassageTimes_2eproto {
  StaticDescriptorInitializer_lm_2fio_2fFirstPassageTimes_2eproto() {
    protobuf_AddDesc_lm_2fio_2fFirstPassageTimes_2eproto();
  }
} static_descriptor_initializer_lm_2fio_2fFirstPassageTimes_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int FirstPassageTimes::kSpeciesFieldNumber;
const int FirstPassageTimes::kSpeciesCountFieldNumber;
const int FirstPassageTimes::kFirstPassageTimeFieldNumber;
#endif  // !_MSC_VER

FirstPassageTimes::FirstPassageTimes()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FirstPassageTimes::InitAsDefaultInstance() {
}

FirstPassageTimes::FirstPassageTimes(const FirstPassageTimes& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FirstPassageTimes::SharedCtor() {
  _cached_size_ = 0;
  species_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FirstPassageTimes::~FirstPassageTimes() {
  SharedDtor();
}

void FirstPassageTimes::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FirstPassageTimes::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FirstPassageTimes::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FirstPassageTimes_descriptor_;
}

const FirstPassageTimes& FirstPassageTimes::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fio_2fFirstPassageTimes_2eproto();  return *default_instance_;
}

FirstPassageTimes* FirstPassageTimes::default_instance_ = NULL;

FirstPassageTimes* FirstPassageTimes::New() const {
  return new FirstPassageTimes;
}

void FirstPassageTimes::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    species_ = 0u;
  }
  species_count_.Clear();
  first_passage_time_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FirstPassageTimes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 species = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &species_)));
          set_has_species();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_species_count;
        break;
      }
      
      // repeated uint32 species_count = 2 [packed = true];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_species_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_species_count())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 18, input, this->mutable_species_count())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_first_passage_time;
        break;
      }
      
      // repeated double first_passage_time = 3 [packed = true];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_first_passage_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_first_passage_time())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 26, input, this->mutable_first_passage_time())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FirstPassageTimes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 species = 1;
  if (has_species()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->species(), output);
  }
  
  // repeated uint32 species_count = 2 [packed = true];
  if (this->species_count_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_species_count_cached_byte_size_);
  }
  for (int i = 0; i < this->species_count_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->species_count(i), output);
  }
  
  // repeated double first_passage_time = 3 [packed = true];
  if (this->first_passage_time_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_first_passage_time_cached_byte_size_);
  }
  for (int i = 0; i < this->first_passage_time_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->first_passage_time(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FirstPassageTimes::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 species = 1;
  if (has_species()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->species(), target);
  }
  
  // repeated uint32 species_count = 2 [packed = true];
  if (this->species_count_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _species_count_cached_byte_size_, target);
  }
  for (int i = 0; i < this->species_count_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->species_count(i), target);
  }
  
  // repeated double first_passage_time = 3 [packed = true];
  if (this->first_passage_time_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _first_passage_time_cached_byte_size_, target);
  }
  for (int i = 0; i < this->first_passage_time_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->first_passage_time(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FirstPassageTimes::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 species = 1;
    if (has_species()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->species());
    }
    
  }
  // repeated uint32 species_count = 2 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->species_count_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->species_count(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _species_count_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  // repeated double first_passage_time = 3 [packed = true];
  {
    int data_size = 0;
    data_size = 8 * this->first_passage_time_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _first_passage_time_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FirstPassageTimes::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FirstPassageTimes* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FirstPassageTimes*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FirstPassageTimes::MergeFrom(const FirstPassageTimes& from) {
  GOOGLE_CHECK_NE(&from, this);
  species_count_.MergeFrom(from.species_count_);
  first_passage_time_.MergeFrom(from.first_passage_time_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_species()) {
      set_species(from.species());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FirstPassageTimes::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FirstPassageTimes::CopyFrom(const FirstPassageTimes& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FirstPassageTimes::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void FirstPassageTimes::Swap(FirstPassageTimes* other) {
  if (other != this) {
    std::swap(species_, other->species_);
    species_count_.Swap(&other->species_count_);
    first_passage_time_.Swap(&other->first_passage_time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FirstPassageTimes::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FirstPassageTimes_descriptor_;
  metadata.reflection = FirstPassageTimes_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

// @@protoc_insertion_point(global_scope)
