// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lm/io/ReactionModel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

namespace {

const ::google::protobuf::Descriptor* ReactionModel_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReactionModel_reflection_ = NULL;
const ::google::protobuf::Descriptor* ReactionModel_Reaction_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReactionModel_Reaction_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lm_2fio_2fReactionModel_2eproto() {
  protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lm/io/ReactionModel.proto");
  GOOGLE_CHECK(file != NULL);
  ReactionModel_descriptor_ = file->message_type(0);
  static const int ReactionModel_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, number_species_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, number_reactions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, initial_species_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, reaction_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, stoichiometric_matrix_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, dependency_matrix_),
  };
  ReactionModel_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReactionModel_descriptor_,
      ReactionModel::default_instance_,
      ReactionModel_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReactionModel));
  ReactionModel_Reaction_descriptor_ = ReactionModel_descriptor_->nested_type(0);
  static const int ReactionModel_Reaction_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel_Reaction, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel_Reaction, rate_constant_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel_Reaction, rate_has_noise_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel_Reaction, rate_noise_variance_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel_Reaction, rate_noise_tau_),
  };
  ReactionModel_Reaction_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReactionModel_Reaction_descriptor_,
      ReactionModel_Reaction::default_instance_,
      ReactionModel_Reaction_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel_Reaction, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReactionModel_Reaction, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReactionModel_Reaction));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lm_2fio_2fReactionModel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReactionModel_descriptor_, &ReactionModel::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReactionModel_Reaction_descriptor_, &ReactionModel_Reaction::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lm_2fio_2fReactionModel_2eproto() {
  delete ReactionModel::default_instance_;
  delete ReactionModel_reflection_;
  delete ReactionModel_Reaction::default_instance_;
  delete ReactionModel_Reaction_reflection_;
}

void protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031lm/io/ReactionModel.proto\022\005lm.io\"\341\002\n\rR"
    "eactionModel\022\026\n\016number_species\030\001 \002(\r\022\030\n\020"
    "number_reactions\030\002 \002(\r\022!\n\025initial_specie"
    "s_count\030\003 \003(\rB\002\020\001\022/\n\010reaction\030\004 \003(\0132\035.lm"
    ".io.ReactionModel.Reaction\022!\n\025stoichiome"
    "tric_matrix\030\005 \003(\005B\002\020\001\022\035\n\021dependency_matr"
    "ix\030\006 \003(\rB\002\020\001\032\207\001\n\010Reaction\022\014\n\004type\030\001 \002(\r\022"
    "\031\n\rrate_constant\030\002 \003(\001B\002\020\001\022\035\n\016rate_has_n"
    "oise\030\003 \001(\010:\005false\022\033\n\023rate_noise_variance"
    "\030\004 \001(\001\022\026\n\016rate_noise_tau\030\005 \001(\001", 390);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lm/io/ReactionModel.proto", &protobuf_RegisterTypes);
  ReactionModel::default_instance_ = new ReactionModel();
  ReactionModel_Reaction::default_instance_ = new ReactionModel_Reaction();
  ReactionModel::default_instance_->InitAsDefaultInstance();
  ReactionModel_Reaction::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lm_2fio_2fReactionModel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lm_2fio_2fReactionModel_2eproto {
  StaticDescriptorInitializer_lm_2fio_2fReactionModel_2eproto() {
    protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto();
  }
} static_descriptor_initializer_lm_2fio_2fReactionModel_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ReactionModel_Reaction::kTypeFieldNumber;
const int ReactionModel_Reaction::kRateConstantFieldNumber;
const int ReactionModel_Reaction::kRateHasNoiseFieldNumber;
const int ReactionModel_Reaction::kRateNoiseVarianceFieldNumber;
const int ReactionModel_Reaction::kRateNoiseTauFieldNumber;
#endif  // !_MSC_VER

ReactionModel_Reaction::ReactionModel_Reaction()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ReactionModel_Reaction::InitAsDefaultInstance() {
}

ReactionModel_Reaction::ReactionModel_Reaction(const ReactionModel_Reaction& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ReactionModel_Reaction::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0u;
  rate_has_noise_ = false;
  rate_noise_variance_ = 0;
  rate_noise_tau_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ReactionModel_Reaction::~ReactionModel_Reaction() {
  SharedDtor();
}

void ReactionModel_Reaction::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReactionModel_Reaction::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReactionModel_Reaction::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReactionModel_Reaction_descriptor_;
}

const ReactionModel_Reaction& ReactionModel_Reaction::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto();  return *default_instance_;
}

ReactionModel_Reaction* ReactionModel_Reaction::default_instance_ = NULL;

ReactionModel_Reaction* ReactionModel_Reaction::New() const {
  return new ReactionModel_Reaction;
}

void ReactionModel_Reaction::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 0u;
    rate_has_noise_ = false;
    rate_noise_variance_ = 0;
    rate_noise_tau_ = 0;
  }
  rate_constant_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReactionModel_Reaction::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_rate_constant;
        break;
      }
      
      // repeated double rate_constant = 2 [packed = true];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_rate_constant:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_rate_constant())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 18, input, this->mutable_rate_constant())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_rate_has_noise;
        break;
      }
      
      // optional bool rate_has_noise = 3 [default = false];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_rate_has_noise:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &rate_has_noise_)));
          set_has_rate_has_noise();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_rate_noise_variance;
        break;
      }
      
      // optional double rate_noise_variance = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_rate_noise_variance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &rate_noise_variance_)));
          set_has_rate_noise_variance();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(41)) goto parse_rate_noise_tau;
        break;
      }
      
      // optional double rate_noise_tau = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_rate_noise_tau:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &rate_noise_tau_)));
          set_has_rate_noise_tau();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ReactionModel_Reaction::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->type(), output);
  }
  
  // repeated double rate_constant = 2 [packed = true];
  if (this->rate_constant_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_rate_constant_cached_byte_size_);
  }
  for (int i = 0; i < this->rate_constant_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->rate_constant(i), output);
  }
  
  // optional bool rate_has_noise = 3 [default = false];
  if (has_rate_has_noise()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->rate_has_noise(), output);
  }
  
  // optional double rate_noise_variance = 4;
  if (has_rate_noise_variance()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->rate_noise_variance(), output);
  }
  
  // optional double rate_noise_tau = 5;
  if (has_rate_noise_tau()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->rate_noise_tau(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ReactionModel_Reaction::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->type(), target);
  }
  
  // repeated double rate_constant = 2 [packed = true];
  if (this->rate_constant_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _rate_constant_cached_byte_size_, target);
  }
  for (int i = 0; i < this->rate_constant_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->rate_constant(i), target);
  }
  
  // optional bool rate_has_noise = 3 [default = false];
  if (has_rate_has_noise()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->rate_has_noise(), target);
  }
  
  // optional double rate_noise_variance = 4;
  if (has_rate_noise_variance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->rate_noise_variance(), target);
  }
  
  // optional double rate_noise_tau = 5;
  if (has_rate_noise_tau()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->rate_noise_tau(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ReactionModel_Reaction::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->type());
    }
    
    // optional bool rate_has_noise = 3 [default = false];
    if (has_rate_has_noise()) {
      total_size += 1 + 1;
    }
    
    // optional double rate_noise_variance = 4;
    if (has_rate_noise_variance()) {
      total_size += 1 + 8;
    }
    
    // optional double rate_noise_tau = 5;
    if (has_rate_noise_tau()) {
      total_size += 1 + 8;
    }
    
  }
  // repeated double rate_constant = 2 [packed = true];
  {
    int data_size = 0;
    data_size = 8 * this->rate_constant_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _rate_constant_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReactionModel_Reaction::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReactionModel_Reaction* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReactionModel_Reaction*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReactionModel_Reaction::MergeFrom(const ReactionModel_Reaction& from) {
  GOOGLE_CHECK_NE(&from, this);
  rate_constant_.MergeFrom(from.rate_constant_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_rate_has_noise()) {
      set_rate_has_noise(from.rate_has_noise());
    }
    if (from.has_rate_noise_variance()) {
      set_rate_noise_variance(from.rate_noise_variance());
    }
    if (from.has_rate_noise_tau()) {
      set_rate_noise_tau(from.rate_noise_tau());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReactionModel_Reaction::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReactionModel_Reaction::CopyFrom(const ReactionModel_Reaction& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReactionModel_Reaction::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void ReactionModel_Reaction::Swap(ReactionModel_Reaction* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    rate_constant_.Swap(&other->rate_constant_);
    std::swap(rate_has_noise_, other->rate_has_noise_);
    std::swap(rate_noise_variance_, other->rate_noise_variance_);
    std::swap(rate_noise_tau_, other->rate_noise_tau_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReactionModel_Reaction::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReactionModel_Reaction_descriptor_;
  metadata.reflection = ReactionModel_Reaction_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ReactionModel::kNumberSpeciesFieldNumber;
const int ReactionModel::kNumberReactionsFieldNumber;
const int ReactionModel::kInitialSpeciesCountFieldNumber;
const int ReactionModel::kReactionFieldNumber;
const int ReactionModel::kStoichiometricMatrixFieldNumber;
const int ReactionModel::kDependencyMatrixFieldNumber;
#endif  // !_MSC_VER

ReactionModel::ReactionModel()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ReactionModel::InitAsDefaultInstance() {
}

ReactionModel::ReactionModel(const ReactionModel& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ReactionModel::SharedCtor() {
  _cached_size_ = 0;
  number_species_ = 0u;
  number_reactions_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ReactionModel::~ReactionModel() {
  SharedDtor();
}

void ReactionModel::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReactionModel::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReactionModel::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReactionModel_descriptor_;
}

const ReactionModel& ReactionModel::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fio_2fReactionModel_2eproto();  return *default_instance_;
}

ReactionModel* ReactionModel::default_instance_ = NULL;

ReactionModel* ReactionModel::New() const {
  return new ReactionModel;
}

void ReactionModel::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    number_species_ = 0u;
    number_reactions_ = 0u;
  }
  initial_species_count_.Clear();
  reaction_.Clear();
  stoichiometric_matrix_.Clear();
  dependency_matrix_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReactionModel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 number_species = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_species_)));
          set_has_number_species();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_number_reactions;
        break;
      }
      
      // required uint32 number_reactions = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_number_reactions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_reactions_)));
          set_has_number_reactions();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_initial_species_count;
        break;
      }
      
      // repeated uint32 initial_species_count = 3 [packed = true];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_initial_species_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_initial_species_count())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 26, input, this->mutable_initial_species_count())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_reaction;
        break;
      }
      
      // repeated .lm.io.ReactionModel.Reaction reaction = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_reaction:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_reaction()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_reaction;
        if (input->ExpectTag(42)) goto parse_stoichiometric_matrix;
        break;
      }
      
      // repeated int32 stoichiometric_matrix = 5 [packed = true];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_stoichiometric_matrix:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_stoichiometric_matrix())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 42, input, this->mutable_stoichiometric_matrix())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_dependency_matrix;
        break;
      }
      
      // repeated uint32 dependency_matrix = 6 [packed = true];
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dependency_matrix:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_dependency_matrix())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 50, input, this->mutable_dependency_matrix())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ReactionModel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 number_species = 1;
  if (has_number_species()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->number_species(), output);
  }
  
  // required uint32 number_reactions = 2;
  if (has_number_reactions()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->number_reactions(), output);
  }
  
  // repeated uint32 initial_species_count = 3 [packed = true];
  if (this->initial_species_count_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_initial_species_count_cached_byte_size_);
  }
  for (int i = 0; i < this->initial_species_count_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->initial_species_count(i), output);
  }
  
  // repeated .lm.io.ReactionModel.Reaction reaction = 4;
  for (int i = 0; i < this->reaction_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->reaction(i), output);
  }
  
  // repeated int32 stoichiometric_matrix = 5 [packed = true];
  if (this->stoichiometric_matrix_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_stoichiometric_matrix_cached_byte_size_);
  }
  for (int i = 0; i < this->stoichiometric_matrix_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->stoichiometric_matrix(i), output);
  }
  
  // repeated uint32 dependency_matrix = 6 [packed = true];
  if (this->dependency_matrix_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_dependency_matrix_cached_byte_size_);
  }
  for (int i = 0; i < this->dependency_matrix_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->dependency_matrix(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ReactionModel::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 number_species = 1;
  if (has_number_species()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->number_species(), target);
  }
  
  // required uint32 number_reactions = 2;
  if (has_number_reactions()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->number_reactions(), target);
  }
  
  // repeated uint32 initial_species_count = 3 [packed = true];
  if (this->initial_species_count_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _initial_species_count_cached_byte_size_, target);
  }
  for (int i = 0; i < this->initial_species_count_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->initial_species_count(i), target);
  }
  
  // repeated .lm.io.ReactionModel.Reaction reaction = 4;
  for (int i = 0; i < this->reaction_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->reaction(i), target);
  }
  
  // repeated int32 stoichiometric_matrix = 5 [packed = true];
  if (this->stoichiometric_matrix_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _stoichiometric_matrix_cached_byte_size_, target);
  }
  for (int i = 0; i < this->stoichiometric_matrix_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->stoichiometric_matrix(i), target);
  }
  
  // repeated uint32 dependency_matrix = 6 [packed = true];
  if (this->dependency_matrix_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _dependency_matrix_cached_byte_size_, target);
  }
  for (int i = 0; i < this->dependency_matrix_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->dependency_matrix(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ReactionModel::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 number_species = 1;
    if (has_number_species()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->number_species());
    }
    
    // required uint32 number_reactions = 2;
    if (has_number_reactions()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->number_reactions());
    }
    
  }
  // repeated uint32 initial_species_count = 3 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->initial_species_count_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->initial_species_count(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _initial_species_count_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  // repeated .lm.io.ReactionModel.Reaction reaction = 4;
  total_size += 1 * this->reaction_size();
  for (int i = 0; i < this->reaction_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->reaction(i));
  }
  
  // repeated int32 stoichiometric_matrix = 5 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->stoichiometric_matrix_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->stoichiometric_matrix(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _stoichiometric_matrix_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  // repeated uint32 dependency_matrix = 6 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->dependency_matrix_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->dependency_matrix(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _dependency_matrix_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReactionModel::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReactionModel* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReactionModel*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReactionModel::MergeFrom(const ReactionModel& from) {
  GOOGLE_CHECK_NE(&from, this);
  initial_species_count_.MergeFrom(from.initial_species_count_);
  reaction_.MergeFrom(from.reaction_);
  stoichiometric_matrix_.MergeFrom(from.stoichiometric_matrix_);
  dependency_matrix_.MergeFrom(from.dependency_matrix_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_number_species()) {
      set_number_species(from.number_species());
    }
    if (from.has_number_reactions()) {
      set_number_reactions(from.number_reactions());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReactionModel::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReactionModel::CopyFrom(const ReactionModel& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReactionModel::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  for (int i = 0; i < reaction_size(); i++) {
    if (!this->reaction(i).IsInitialized()) return false;
  }
  return true;
}

void ReactionModel::Swap(ReactionModel* other) {
  if (other != this) {
    std::swap(number_species_, other->number_species_);
    std::swap(number_reactions_, other->number_reactions_);
    initial_species_count_.Swap(&other->initial_species_count_);
    reaction_.Swap(&other->reaction_);
    stoichiometric_matrix_.Swap(&other->stoichiometric_matrix_);
    dependency_matrix_.Swap(&other->dependency_matrix_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReactionModel::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReactionModel_descriptor_;
  metadata.reflection = ReactionModel_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

// @@protoc_insertion_point(global_scope)
