// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lm/io/SpeciesCounts.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace io {

namespace {

const ::google::protobuf::Descriptor* SpeciesCounts_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpeciesCounts_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lm_2fio_2fSpeciesCounts_2eproto() {
  protobuf_AddDesc_lm_2fio_2fSpeciesCounts_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lm/io/SpeciesCounts.proto");
  GOOGLE_CHECK(file != NULL);
  SpeciesCounts_descriptor_ = file->message_type(0);
  static const int SpeciesCounts_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpeciesCounts, number_species_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpeciesCounts, number_entries_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpeciesCounts, species_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpeciesCounts, time_),
  };
  SpeciesCounts_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SpeciesCounts_descriptor_,
      SpeciesCounts::default_instance_,
      SpeciesCounts_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpeciesCounts, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpeciesCounts, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SpeciesCounts));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lm_2fio_2fSpeciesCounts_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SpeciesCounts_descriptor_, &SpeciesCounts::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lm_2fio_2fSpeciesCounts_2eproto() {
  delete SpeciesCounts::default_instance_;
  delete SpeciesCounts_reflection_;
}

void protobuf_AddDesc_lm_2fio_2fSpeciesCounts_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031lm/io/SpeciesCounts.proto\022\005lm.io\"l\n\rSp"
    "eciesCounts\022\026\n\016number_species\030\001 \002(\r\022\026\n\016n"
    "umber_entries\030\002 \002(\r\022\031\n\rspecies_count\030\003 \003"
    "(\rB\002\020\001\022\020\n\004time\030\004 \003(\001B\002\020\001", 144);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lm/io/SpeciesCounts.proto", &protobuf_RegisterTypes);
  SpeciesCounts::default_instance_ = new SpeciesCounts();
  SpeciesCounts::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lm_2fio_2fSpeciesCounts_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lm_2fio_2fSpeciesCounts_2eproto {
  StaticDescriptorInitializer_lm_2fio_2fSpeciesCounts_2eproto() {
    protobuf_AddDesc_lm_2fio_2fSpeciesCounts_2eproto();
  }
} static_descriptor_initializer_lm_2fio_2fSpeciesCounts_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SpeciesCounts::kNumberSpeciesFieldNumber;
const int SpeciesCounts::kNumberEntriesFieldNumber;
const int SpeciesCounts::kSpeciesCountFieldNumber;
const int SpeciesCounts::kTimeFieldNumber;
#endif  // !_MSC_VER

SpeciesCounts::SpeciesCounts()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SpeciesCounts::InitAsDefaultInstance() {
}

SpeciesCounts::SpeciesCounts(const SpeciesCounts& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SpeciesCounts::SharedCtor() {
  _cached_size_ = 0;
  number_species_ = 0u;
  number_entries_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SpeciesCounts::~SpeciesCounts() {
  SharedDtor();
}

void SpeciesCounts::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SpeciesCounts::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpeciesCounts::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpeciesCounts_descriptor_;
}

const SpeciesCounts& SpeciesCounts::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lm_2fio_2fSpeciesCounts_2eproto();  return *default_instance_;
}

SpeciesCounts* SpeciesCounts::default_instance_ = NULL;

SpeciesCounts* SpeciesCounts::New() const {
  return new SpeciesCounts;
}

void SpeciesCounts::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    number_species_ = 0u;
    number_entries_ = 0u;
  }
  species_count_.Clear();
  time_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SpeciesCounts::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 number_species = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_species_)));
          set_has_number_species();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_number_entries;
        break;
      }
      
      // required uint32 number_entries = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_number_entries:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_entries_)));
          set_has_number_entries();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_species_count;
        break;
      }
      
      // repeated uint32 species_count = 3 [packed = true];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_species_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_species_count())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 26, input, this->mutable_species_count())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_time;
        break;
      }
      
      // repeated double time = 4 [packed = true];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_time())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 34, input, this->mutable_time())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SpeciesCounts::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 number_species = 1;
  if (has_number_species()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->number_species(), output);
  }
  
  // required uint32 number_entries = 2;
  if (has_number_entries()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->number_entries(), output);
  }
  
  // repeated uint32 species_count = 3 [packed = true];
  if (this->species_count_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_species_count_cached_byte_size_);
  }
  for (int i = 0; i < this->species_count_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->species_count(i), output);
  }
  
  // repeated double time = 4 [packed = true];
  if (this->time_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_time_cached_byte_size_);
  }
  for (int i = 0; i < this->time_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->time(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SpeciesCounts::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 number_species = 1;
  if (has_number_species()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->number_species(), target);
  }
  
  // required uint32 number_entries = 2;
  if (has_number_entries()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->number_entries(), target);
  }
  
  // repeated uint32 species_count = 3 [packed = true];
  if (this->species_count_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _species_count_cached_byte_size_, target);
  }
  for (int i = 0; i < this->species_count_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->species_count(i), target);
  }
  
  // repeated double time = 4 [packed = true];
  if (this->time_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _time_cached_byte_size_, target);
  }
  for (int i = 0; i < this->time_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->time(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SpeciesCounts::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 number_species = 1;
    if (has_number_species()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->number_species());
    }
    
    // required uint32 number_entries = 2;
    if (has_number_entries()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->number_entries());
    }
    
  }
  // repeated uint32 species_count = 3 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->species_count_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->species_count(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _species_count_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  // repeated double time = 4 [packed = true];
  {
    int data_size = 0;
    data_size = 8 * this->time_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _time_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpeciesCounts::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SpeciesCounts* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SpeciesCounts*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SpeciesCounts::MergeFrom(const SpeciesCounts& from) {
  GOOGLE_CHECK_NE(&from, this);
  species_count_.MergeFrom(from.species_count_);
  time_.MergeFrom(from.time_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_number_species()) {
      set_number_species(from.number_species());
    }
    if (from.has_number_entries()) {
      set_number_entries(from.number_entries());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SpeciesCounts::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpeciesCounts::CopyFrom(const SpeciesCounts& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpeciesCounts::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void SpeciesCounts::Swap(SpeciesCounts* other) {
  if (other != this) {
    std::swap(number_species_, other->number_species_);
    std::swap(number_entries_, other->number_entries_);
    species_count_.Swap(&other->species_count_);
    time_.Swap(&other->time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SpeciesCounts::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpeciesCounts_descriptor_;
  metadata.reflection = SpeciesCounts_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace lm

// @@protoc_insertion_point(global_scope)
