// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm/message/SimulationParameters.proto

#ifndef PROTOBUF_lm_2fmessage_2fSimulationParameters_2eproto__INCLUDED
#define PROTOBUF_lm_2fmessage_2fSimulationParameters_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace lm {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lm_2fmessage_2fSimulationParameters_2eproto();
void protobuf_AssignDesc_lm_2fmessage_2fSimulationParameters_2eproto();
void protobuf_ShutdownFile_lm_2fmessage_2fSimulationParameters_2eproto();

class SimulationParameters;

// ===================================================================

class SimulationParameters : public ::google::protobuf::Message {
 public:
  SimulationParameters();
  virtual ~SimulationParameters();
  
  SimulationParameters(const SimulationParameters& from);
  
  inline SimulationParameters& operator=(const SimulationParameters& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SimulationParameters& default_instance();
  
  void Swap(SimulationParameters* other);
  
  // implements Message ----------------------------------------------
  
  SimulationParameters* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SimulationParameters& from);
  void MergeFrom(const SimulationParameters& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated string key = 1;
  inline int key_size() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 1;
  inline const ::std::string& key(int index) const;
  inline ::std::string* mutable_key(int index);
  inline void set_key(int index, const ::std::string& value);
  inline void set_key(int index, const char* value);
  inline void set_key(int index, const char* value, size_t size);
  inline ::std::string* add_key();
  inline void add_key(const ::std::string& value);
  inline void add_key(const char* value);
  inline void add_key(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& key() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_key();
  
  // repeated string value = 2;
  inline int value_size() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline const ::std::string& value(int index) const;
  inline ::std::string* mutable_value(int index);
  inline void set_value(int index, const ::std::string& value);
  inline void set_value(int index, const char* value);
  inline void set_value(int index, const char* value, size_t size);
  inline ::std::string* add_value();
  inline void add_value(const ::std::string& value);
  inline void add_value(const char* value);
  inline void add_value(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& value() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_value();
  
  // @@protoc_insertion_point(class_scope:lm.message.SimulationParameters)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> key_;
  ::google::protobuf::RepeatedPtrField< ::std::string> value_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_lm_2fmessage_2fSimulationParameters_2eproto();
  friend void protobuf_AssignDesc_lm_2fmessage_2fSimulationParameters_2eproto();
  friend void protobuf_ShutdownFile_lm_2fmessage_2fSimulationParameters_2eproto();
  
  void InitAsDefaultInstance();
  static SimulationParameters* default_instance_;
};
// ===================================================================


// ===================================================================

// SimulationParameters

// repeated string key = 1;
inline int SimulationParameters::key_size() const {
  return key_.size();
}
inline void SimulationParameters::clear_key() {
  key_.Clear();
}
inline const ::std::string& SimulationParameters::key(int index) const {
  return key_.Get(index);
}
inline ::std::string* SimulationParameters::mutable_key(int index) {
  return key_.Mutable(index);
}
inline void SimulationParameters::set_key(int index, const ::std::string& value) {
  key_.Mutable(index)->assign(value);
}
inline void SimulationParameters::set_key(int index, const char* value) {
  key_.Mutable(index)->assign(value);
}
inline void SimulationParameters::set_key(int index, const char* value, size_t size) {
  key_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SimulationParameters::add_key() {
  return key_.Add();
}
inline void SimulationParameters::add_key(const ::std::string& value) {
  key_.Add()->assign(value);
}
inline void SimulationParameters::add_key(const char* value) {
  key_.Add()->assign(value);
}
inline void SimulationParameters::add_key(const char* value, size_t size) {
  key_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SimulationParameters::key() const {
  return key_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SimulationParameters::mutable_key() {
  return &key_;
}

// repeated string value = 2;
inline int SimulationParameters::value_size() const {
  return value_.size();
}
inline void SimulationParameters::clear_value() {
  value_.Clear();
}
inline const ::std::string& SimulationParameters::value(int index) const {
  return value_.Get(index);
}
inline ::std::string* SimulationParameters::mutable_value(int index) {
  return value_.Mutable(index);
}
inline void SimulationParameters::set_value(int index, const ::std::string& value) {
  value_.Mutable(index)->assign(value);
}
inline void SimulationParameters::set_value(int index, const char* value) {
  value_.Mutable(index)->assign(value);
}
inline void SimulationParameters::set_value(int index, const char* value, size_t size) {
  value_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SimulationParameters::add_value() {
  return value_.Add();
}
inline void SimulationParameters::add_value(const ::std::string& value) {
  value_.Add()->assign(value);
}
inline void SimulationParameters::add_value(const char* value) {
  value_.Add()->assign(value);
}
inline void SimulationParameters::add_value(const char* value, size_t size) {
  value_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SimulationParameters::value() const {
  return value_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SimulationParameters::mutable_value() {
  return &value_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2fmessage_2fSimulationParameters_2eproto__INCLUDED
