/*
 * University of Illinois Open Source License
 * Copyright 2012-2016 Roberts Group,
 * All rights reserved.
 *
 * Developed by: Roberts Group
 *                  Johns Hopkins University
 *                  http://biophysics.jhu.edu/roberts/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the Software), to deal with
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to
 * do so, subject to the following conditions:
 *
 * - Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimers.
 *
 * - Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimers in the documentation
 * and/or other materials provided with the distribution.
 *
 * - Neither the names of the Roberts Group, Johns Hopkins University,
 * nor the names of its contributors may be used to endorse or
 * promote products derived from this Software without specific prior written
 * permission.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS WITH THE SOFTWARE.
 *
 * Author(s): Elijah Roberts, Max Klein
 */
syntax = "proto2";
package lm.fflux.input;

import "lm/fflux/input/FFluxPhaseLimit.proto";
import "lm/input/OutputOptions.proto";
import "lm/input/Tilings.proto";

message FFluxStage {
    required uint64 id                                         = 1;

    optional lm.input.Tiling tiling                            = 11;
    optional uint32 basin_index                                = 12 [default=0];

    /*
     * - Stopping conditions for each forward flux phase. Can be specified one of two ways (an error will be raised if more than one way is used)
     *     - If a pilot_stage has been set, the phase limits will be set dynamically based on the results of the pilot stage and precision_goal from FFluxSimulationParameters
     *     - A manually specified list of phase limits, one per interfaces in this stage's tiling
     *         - If there are fewer limits than interfaces, the last limit will be repeated to make up the difference
     *             - This is useful for specifying one limit for phase zero and another limit for the rest of the phases
     *         - If there are more limits than interfaces, an error will be raised
     */
    repeated lm.fflux.input.FFluxPhaseLimit fflux_phase_limits = 21;

    optional FFluxStage pilot_stage                            = 31;

    optional lm.input.OutputOptions output_options             = 101;
}

message FFluxStageList {
    repeated lm.fflux.input.FFluxStage fflux_stages = 1;
}
